module SignwellSDK
  module Resources
    class V1
      class DocumentTemplates
        def list: (
          ?limit: Integer,
          ?page: Integer,
          ?request_options: SignwellSDK::request_opts
        ) -> SignwellSDK::Models::V1::DocumentTemplateListResponse

        def initialize: (client: SignwellSDK::Client) -> void
      end
    end
  end
end
