module SignwellSDK
  module Resources
    class V1
      class Documents
        def list: (
          ?limit: Integer,
          ?page: Integer,
          ?request_options: SignwellSDK::request_opts
        ) -> SignwellSDK::Models::V1::DocumentListResponse

        def remind: (
          String id,
          ?recipients: ::Array[SignwellSDK::V1::DocumentRemindParams::Recipient],
          ?request_options: SignwellSDK::request_opts
        ) -> nil

        def retrieve_nom151_certificate: (
          String id,
          ?object_only: bool,
          ?url_only: bool,
          ?request_options: SignwellSDK::request_opts
        ) -> SignwellSDK::Models::V1::document_retrieve_nom151_certificate_response

        def initialize: (client: SignwellSDK::Client) -> void
      end
    end
  end
end
