=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SignWell::APIApplicationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'APIApplicationApi' do
  before do
    # run before each test
    @api_instance = SignWell::APIApplicationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of APIApplicationApi' do
    it 'should create an instance of APIApplicationApi' do
      expect(@api_instance).to be_instance_of(SignWell::APIApplicationApi)
    end
  end

  # unit tests for delete_api_application
  # Delete API Application
  # Deletes an API Application from an account. Supply the unique Application ID from either the Create API Application response or the API Application edit page
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_api_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_api_application
  # Get API Application
  # Gets the details of a specific API Application within an account. Supply the unique Application ID from either the Create API Application response or the API Application edit page.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_api_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
