=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Integration tests for SignWell::Resources::DocumentApi
# Auto-generated - tests run against Prism mock server (localhost:4010)
RSpec.describe SignWell::Resources::DocumentApi, :prism do
  before(:all) do
    prism_url = URI(ENV.fetch('PRISM_URL', 'http://localhost:4010'))
    SignWell.configure do |config|
      config.scheme = prism_url.scheme
      config.host = "#{prism_url.host}:#{prism_url.port}"
      config.api_key['X-Api-Key'] = 'test-api-key'
      
    end
    @api = SignWell::Resources::DocumentApi.new
    @test_id = '00000000-0000-0000-0000-000000000000'
  end

  describe '#create_document' do
    it 'returns DocumentResponse' do
      body = SignWell::DocumentRequest.new({files: [SignWell::FilesInner.new({name: 'name_example'})], recipients: [SignWell::RecipientsInner.new({id: 'id_example', email: 'signer@example.com'})]})
      result = @api.create_document(body)
      expect(result).not_to be_nil
    end
  end

  describe '#create_document_from_template' do
    it 'returns DocumentFromTemplateResponse' do
      body = SignWell::DocumentFromTemplateRequest.new({recipients: [SignWell::TemplateRecipientsInner.new({id: 'id_example', email: 'signer@example.com'})]})
      result = @api.create_document_from_template(body)
      expect(result).not_to be_nil
    end
  end

  describe '#delete_document' do
    it 'succeeds' do
      expect { @api.delete_document(@test_id) }.not_to raise_error
    end
  end

  describe '#get_completed_pdf' do
    it 'returns CompletedPdfResponse' do
      result = @api.get_completed_pdf(@test_id)
      expect(result).not_to be_nil
    end
  end

  describe '#get_document' do
    it 'returns DocumentResponse' do
      result = @api.get_document(@test_id)
      expect(result).not_to be_nil
    end
  end

  describe '#send_document' do
    it 'returns DocumentResponse' do
      body = SignWell::UpdateDocumentAndSendRequest.new
      result = @api.send_document(@test_id, body)
      expect(result).not_to be_nil
    end
  end

  describe '#send_reminder' do
    it 'succeeds' do
      body = SignWell::SendReminderRequest.new
      expect { @api.send_reminder(@test_id, body) }.not_to raise_error
    end
  end

end
