=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SignWell::MeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MeApi' do
  before do
    # run before each test
    @api_instance = SignWell::MeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MeApi' do
    it 'should create an instance of MeApi' do
      expect(@api_instance).to be_instance_of(SignWell::MeApi)
    end
  end

  # unit tests for get_me
  # Get credentials
  # Retrieves the account information associated with the API key being used.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_me test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
