=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SignWell::RegionalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RegionalApi' do
  before do
    # run before each test
    @api_instance = SignWell::RegionalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RegionalApi' do
    it 'should create an instance of RegionalApi' do
      expect(@api_instance).to be_instance_of(SignWell::RegionalApi)
    end
  end

  # unit tests for get_nom151_certificate
  # MX – NOM-151 Certificate
  # Download NOM-151 certificate for a completed document. Returns a ZIP file, download URL, or raw certificate data based on query parameters.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :url_only If true, returns JSON with download URL instead of downloading the file
  # @option opts [Boolean] :object_only 
  # @return [Nom151UrlResponse]
  describe 'get_nom151_certificate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
