# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'

# Integration tests for SignWell::Resources::TemplateApi
# Auto-generated - tests run against Prism mock server (localhost:4010)
RSpec.describe SignWell::Resources::TemplateApi, :prism do
  before(:all) do
    prism_url = URI(ENV.fetch('PRISM_URL', 'http://localhost:4010'))
    SignWell.configure do |config|
      config.scheme = prism_url.scheme
      config.host = "#{prism_url.host}:#{prism_url.port}"
      config.api_key['X-Api-Key'] = 'test-api-key'
    end
    @api = SignWell::Resources::TemplateApi.new
    @test_id = '00000000-0000-0000-0000-000000000000'
  end

  describe '#create_template' do
    it 'returns DocumentTemplateResponse' do
      body = SignWell::DocumentTemplateRequest.new({ files: [SignWell::FilesInner.new({ name: 'name_example' })],
                                                     placeholders: [SignWell::PlaceholdersInner.new({ id: 'id_example',
                                                                                                      name: 'name_example' })] })
      result = @api.create_template(body)
      expect(result).not_to be_nil
    end
  end

  describe '#delete_template' do
    it 'succeeds' do
      expect { @api.delete_template(@test_id) }.not_to raise_error
    end
  end

  describe '#get_template' do
    it 'returns DocumentTemplateResponse' do
      result = @api.get_template(@test_id)
      expect(result).not_to be_nil
    end
  end

  describe '#update_template' do
    it 'returns DocumentTemplateResponse' do
      body = SignWell::DocumentTemplateUpdateRequest.new
      result = @api.update_template(@test_id, body)
      expect(result).not_to be_nil
    end
  end
end
