=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Integration tests for SignWell::Resources::WebhooksApi
# Auto-generated - tests run against Prism mock server (localhost:4010)
RSpec.describe SignWell::Resources::WebhooksApi, :prism do
  before(:all) do
    prism_url = URI(ENV.fetch('PRISM_URL', 'http://localhost:4010'))
    SignWell.configure do |config|
      config.scheme = prism_url.scheme
      config.host = "#{prism_url.host}:#{prism_url.port}"
      config.api_key['X-Api-Key'] = 'test-api-key'
      
    end
    @api = SignWell::Resources::WebhooksApi.new
    @test_id = '00000000-0000-0000-0000-000000000000'
  end

  describe '#create_webhook' do
    it 'succeeds' do
      body = SignWell::CreateWebhookRequest.new({callback_url: 'https://example.com/webhook'})
      expect { @api.create_webhook(body) }.not_to raise_error
    end
  end

  describe '#delete_webhook' do
    it 'succeeds' do
      expect { @api.delete_webhook(@test_id) }.not_to raise_error
    end
  end

  describe '#list_webhooks' do
    it 'succeeds' do
      expect { @api.list_webhooks }.not_to raise_error
    end
  end

end
