# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::AccountInfoResponsePreferences
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::AccountInfoResponsePreferences do
  let(:instance) { SignWell::Models::AccountInfoResponsePreferences.allocate }

  describe 'test an instance of AccountInfoResponsePreferences' do
    it 'should create an instance of AccountInfoResponsePreferences' do
      expect(instance).to be_a(SignWell::Models::AccountInfoResponsePreferences)
    end
  end

  describe 'test attribute "date_format"' do
    it 'should work' do
      expect(instance).to respond_to(:date_format)
    end
  end

  describe 'test attribute "days_until_links_expire"' do
    it 'should work' do
      expect(instance).to respond_to(:days_until_links_expire)
    end
  end

  describe 'test attribute "disable_apply_everywhere"' do
    it 'should work' do
      expect(instance).to respond_to(:disable_apply_everywhere)
    end
  end

  describe 'test attribute "disable_apply_everywhere_effective"' do
    it 'should work' do
      expect(instance).to respond_to(:disable_apply_everywhere_effective)
    end
  end

  describe 'test attribute "disable_drawn_signatures"' do
    it 'should work' do
      expect(instance).to respond_to(:disable_drawn_signatures)
    end
  end

  describe 'test attribute "disable_typed_signatures"' do
    it 'should work' do
      expect(instance).to respond_to(:disable_typed_signatures)
    end
  end

  describe 'test attribute "disable_uploaded_signatures"' do
    it 'should work' do
      expect(instance).to respond_to(:disable_uploaded_signatures)
    end
  end

  describe 'test attribute "enable_redirect"' do
    it 'should work' do
      expect(instance).to respond_to(:enable_redirect)
    end
  end

  describe 'test attribute "hide_document_id_in_audit"' do
    it 'should work' do
      expect(instance).to respond_to(:hide_document_id_in_audit)
    end
  end

  describe 'test attribute "mute_branding"' do
    it 'should work' do
      expect(instance).to respond_to(:mute_branding)
    end
  end

  describe 'test attribute "redirect_url"' do
    it 'should work' do
      expect(instance).to respond_to(:redirect_url)
    end
  end

  describe 'test attribute "separate_audit_pdf"' do
    it 'should work' do
      expect(instance).to respond_to(:separate_audit_pdf)
    end
  end

  describe 'test attribute "separate_completed_file"' do
    it 'should work' do
      expect(instance).to respond_to(:separate_completed_file)
    end
  end

  describe 'test attribute "enable_nom151_compliance"' do
    it 'should work' do
      expect(instance).to respond_to(:enable_nom151_compliance)
    end
  end
end
