# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::ApiApplicationResponsePreferences
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::ApiApplicationResponsePreferences do
  let(:instance) { SignWell::Models::ApiApplicationResponsePreferences.allocate }

  describe 'test an instance of ApiApplicationResponsePreferences' do
    it 'should create an instance of ApiApplicationResponsePreferences' do
      expect(instance).to be_a(SignWell::Models::ApiApplicationResponsePreferences)
    end
  end

  describe 'test attribute "button_text_color"' do
    it 'should work' do
      expect(instance).to respond_to(:button_text_color)
    end
  end

  describe 'test attribute "buttons_border_radius"' do
    it 'should work' do
      expect(instance).to respond_to(:buttons_border_radius)
    end
  end

  describe 'test attribute "custom_logo_file"' do
    it 'should work' do
      expect(instance).to respond_to(:custom_logo_file)
    end
  end

  describe 'test attribute "link_text_color"' do
    it 'should work' do
      expect(instance).to respond_to(:link_text_color)
    end
  end

  describe 'test attribute "primary_color"' do
    it 'should work' do
      expect(instance).to respond_to(:primary_color)
    end
  end
end
