# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::BulkSendValidateCsvResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::BulkSendValidateCsvResponse do
  let(:instance) { SignWell::Models::BulkSendValidateCsvResponse.allocate }

  describe 'test an instance of BulkSendValidateCsvResponse' do
    it 'should create an instance of BulkSendValidateCsvResponse' do
      expect(instance).to be_a(SignWell::Models::BulkSendValidateCsvResponse)
    end
  end

  describe 'test attribute "bulk_send_csv"' do
    it 'should work' do
      expect(instance).to respond_to(:bulk_send_csv)
    end
  end

  describe 'test attribute "template_ids"' do
    it 'should work' do
      expect(instance).to respond_to(:template_ids)
    end
  end

  describe 'test attribute "skip_row_errors"' do
    it 'should work' do
      expect(instance).to respond_to(:skip_row_errors)
    end
  end

  describe 'test attribute "api_application_id"' do
    it 'should work' do
      expect(instance).to respond_to(:api_application_id)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      expect(instance).to respond_to(:subject)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "apply_signing_order"' do
    it 'should work' do
      expect(instance).to respond_to(:apply_signing_order)
    end
  end
end
