# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::BulkSendCreateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::BulkSendCreateResponse do
  let(:instance) { SignWell::Models::BulkSendCreateResponse.allocate }

  describe 'test an instance of BulkSendCreateResponse' do
    it 'should create an instance of BulkSendCreateResponse' do
      expect(instance).to be_a(SignWell::Models::BulkSendCreateResponse)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance).to respond_to(:id)
    end
  end

  describe 'test attribute "template_ids"' do
    it 'should work' do
      expect(instance).to respond_to(:template_ids)
    end
  end

  describe 'test attribute "api_application_id"' do
    it 'should work' do
      expect(instance).to respond_to(:api_application_id)
    end
  end

  describe 'test attribute "documents_count"' do
    it 'should work' do
      expect(instance).to respond_to(:documents_count)
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      expect(instance).to respond_to(:created_at)
    end
  end

  describe 'test attribute "user_id"' do
    it 'should work' do
      expect(instance).to respond_to(:user_id)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      expect(instance).to respond_to(:status)
    end
  end
end
