# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::CopiedPlaceholdersInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::CopiedPlaceholdersInner do
  let(:instance) { SignWell::Models::CopiedPlaceholdersInner.allocate }

  describe 'test an instance of CopiedPlaceholdersInner' do
    it 'should create an instance of CopiedPlaceholdersInner' do
      expect(instance).to be_a(SignWell::Models::CopiedPlaceholdersInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "preassigned_recipient_name"' do
    it 'should work' do
      expect(instance).to respond_to(:preassigned_recipient_name)
    end
  end

  describe 'test attribute "preassigned_recipient_email"' do
    it 'should work' do
      expect(instance).to respond_to(:preassigned_recipient_email)
    end
  end
end
