# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::CopiedContactsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::CopiedContactsInner do
  let(:instance) { SignWell::Models::CopiedContactsInner.allocate }

  describe 'test an instance of CopiedContactsInner' do
    it 'should create an instance of CopiedContactsInner' do
      expect(instance).to be_a(SignWell::Models::CopiedContactsInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      expect(instance).to respond_to(:email)
    end
  end
end
