# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::DetailedOption
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::DetailedOption do
  let(:instance) { SignWell::Models::DetailedOption.allocate }

  describe 'test an instance of DetailedOption' do
    it 'should create an instance of DetailedOption' do
      expect(instance).to be_a(SignWell::Models::DetailedOption)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "api_id"' do
    it 'should work' do
      expect(instance).to respond_to(:api_id)
    end
  end

  describe 'test attribute "is_other"' do
    it 'should work' do
      expect(instance).to respond_to(:is_other)
    end
  end
end
