# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::DocumentResponseRecipientsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::DocumentResponseRecipientsInner do
  let(:instance) { SignWell::Models::DocumentResponseRecipientsInner.allocate }

  describe 'test an instance of DocumentResponseRecipientsInner' do
    it 'should create an instance of DocumentResponseRecipientsInner' do
      expect(instance).to be_a(SignWell::Models::DocumentResponseRecipientsInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance).to respond_to(:id)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      expect(instance).to respond_to(:email)
    end
  end

  describe 'test attribute "body"' do
    it 'should work' do
      expect(instance).to respond_to(:body)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      expect(instance).to respond_to(:subject)
    end
  end

  describe 'test attribute "send_email"' do
    it 'should work' do
      expect(instance).to respond_to(:send_email)
    end
  end

  describe 'test attribute "send_email_delay"' do
    it 'should work' do
      expect(instance).to respond_to(:send_email_delay)
    end
  end

  describe 'test attribute "signing_order"' do
    it 'should work' do
      expect(instance).to respond_to(:signing_order)
    end
  end

  describe 'test attribute "signing_url"' do
    it 'should work' do
      expect(instance).to respond_to(:signing_url)
    end
  end

  describe 'test attribute "bounced"' do
    it 'should work' do
      expect(instance).to respond_to(:bounced)
    end
  end

  describe 'test attribute "bounced_details"' do
    it 'should work' do
      expect(instance).to respond_to(:bounced_details)
    end
  end

  describe 'test attribute "attachment_requests"' do
    it 'should work' do
      expect(instance).to respond_to(:attachment_requests)
    end
  end

  describe 'test attribute "passcode"' do
    it 'should work' do
      expect(instance).to respond_to(:passcode)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      expect(instance).to respond_to(:status)
    end
  end
end
