# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::DocumentFromTemplateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::DocumentFromTemplateResponse do
  let(:instance) { SignWell::Models::DocumentFromTemplateResponse.allocate }

  describe 'test an instance of DocumentFromTemplateResponse' do
    it 'should create an instance of DocumentFromTemplateResponse' do
      expect(instance).to be_a(SignWell::Models::DocumentFromTemplateResponse)
    end
  end

  describe 'test attribute "test_mode"' do
    it 'should work' do
      expect(instance).to respond_to(:test_mode)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance).to respond_to(:id)
    end
  end

  describe 'test attribute "template_id"' do
    it 'should work' do
      expect(instance).to respond_to(:template_id)
    end
  end

  describe 'test attribute "template_ids"' do
    it 'should work' do
      expect(instance).to respond_to(:template_ids)
    end
  end

  describe 'test attribute "api_application_id"' do
    it 'should work' do
      expect(instance).to respond_to(:api_application_id)
    end
  end

  describe 'test attribute "requester_email_address"' do
    it 'should work' do
      expect(instance).to respond_to(:requester_email_address)
    end
  end

  describe 'test attribute "custom_requester_name"' do
    it 'should work' do
      expect(instance).to respond_to(:custom_requester_name)
    end
  end

  describe 'test attribute "custom_requester_email"' do
    it 'should work' do
      expect(instance).to respond_to(:custom_requester_email)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      expect(instance).to respond_to(:subject)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      expect(instance).to respond_to(:metadata)
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      expect(instance).to respond_to(:created_at)
    end
  end

  describe 'test attribute "updated_at"' do
    it 'should work' do
      expect(instance).to respond_to(:updated_at)
    end
  end

  describe 'test attribute "recipients"' do
    it 'should work' do
      expect(instance).to respond_to(:recipients)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      expect(instance).to respond_to(:status)
    end
  end

  describe 'test attribute "reminders"' do
    it 'should work' do
      expect(instance).to respond_to(:reminders)
    end
  end

  describe 'test attribute "archived"' do
    it 'should work' do
      expect(instance).to respond_to(:archived)
    end
  end

  describe 'test attribute "embedded"' do
    it 'should work' do
      expect(instance).to respond_to(:embedded)
    end
  end

  describe 'test attribute "embedded_edit_url"' do
    it 'should work' do
      expect(instance).to respond_to(:embedded_edit_url)
    end
  end

  describe 'test attribute "apply_signing_order"' do
    it 'should work' do
      expect(instance).to respond_to(:apply_signing_order)
    end
  end

  describe 'test attribute "redirect_url"' do
    it 'should work' do
      expect(instance).to respond_to(:redirect_url)
    end
  end

  describe 'test attribute "decline_redirect_url"' do
    it 'should work' do
      expect(instance).to respond_to(:decline_redirect_url)
    end
  end

  describe 'test attribute "language"' do
    it 'should work' do
      expect(instance).to respond_to(:language)
    end
  end

  describe 'test attribute "expires_in"' do
    it 'should work' do
      expect(instance).to respond_to(:expires_in)
    end
  end

  describe 'test attribute "attachment_requests"' do
    it 'should work' do
      expect(instance).to respond_to(:attachment_requests)
    end
  end

  describe 'test attribute "files"' do
    it 'should work' do
      expect(instance).to respond_to(:files)
    end
  end

  describe 'test attribute "copied_contacts"' do
    it 'should work' do
      expect(instance).to respond_to(:copied_contacts)
    end
  end

  describe 'test attribute "fields"' do
    it 'should work' do
      expect(instance).to respond_to(:fields)
    end
  end

  describe 'test attribute "allow_decline"' do
    it 'should work' do
      expect(instance).to respond_to(:allow_decline)
    end
  end

  describe 'test attribute "allow_reassign"' do
    it 'should work' do
      expect(instance).to respond_to(:allow_reassign)
    end
  end

  describe 'test attribute "labels"' do
    it 'should work' do
      expect(instance).to respond_to(:labels)
    end
  end
end
