# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::DocumentFromTemplateResponseFieldsInnerInnerRecipient
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::DocumentFromTemplateResponseFieldsInnerInnerRecipient do
  let(:instance) { SignWell::DocumentFromTemplateResponseFieldsInnerInnerRecipient.new }

  describe 'test an instance of DocumentFromTemplateResponseFieldsInnerInnerRecipient' do
    it 'should create an instance of DocumentFromTemplateResponseFieldsInnerInnerRecipient' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SignWell::DocumentFromTemplateResponseFieldsInnerInnerRecipient)
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "role"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
