# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::DocumentFromTemplateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::DocumentFromTemplateRequest do
  let(:instance) { SignWell::Models::DocumentFromTemplateRequest.allocate }

  describe 'test an instance of DocumentFromTemplateRequest' do
    it 'should create an instance of DocumentFromTemplateRequest' do
      expect(instance).to be_a(SignWell::Models::DocumentFromTemplateRequest)
    end
  end

  describe 'test attribute "test_mode"' do
    it 'should work' do
      expect(instance).to respond_to(:test_mode)
    end
  end

  describe 'test attribute "template_id"' do
    it 'should work' do
      expect(instance).to respond_to(:template_id)
    end
  end

  describe 'test attribute "template_ids"' do
    it 'should work' do
      expect(instance).to respond_to(:template_ids)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      expect(instance).to respond_to(:subject)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "recipients"' do
    it 'should work' do
      expect(instance).to respond_to(:recipients)
    end
  end

  describe 'test attribute "exclude_placeholders"' do
    it 'should work' do
      expect(instance).to respond_to(:exclude_placeholders)
    end
  end

  describe 'test attribute "draft"' do
    it 'should work' do
      expect(instance).to respond_to(:draft)
    end
  end

  describe 'test attribute "with_signature_page"' do
    it 'should work' do
      expect(instance).to respond_to(:with_signature_page)
    end
  end

  describe 'test attribute "expires_in"' do
    it 'should work' do
      expect(instance).to respond_to(:expires_in)
    end
  end

  describe 'test attribute "reminders"' do
    it 'should work' do
      expect(instance).to respond_to(:reminders)
    end
  end

  describe 'test attribute "apply_signing_order"' do
    it 'should work' do
      expect(instance).to respond_to(:apply_signing_order)
    end
  end

  describe 'test attribute "api_application_id"' do
    it 'should work' do
      expect(instance).to respond_to(:api_application_id)
    end
  end

  describe 'test attribute "embedded_signing"' do
    it 'should work' do
      expect(instance).to respond_to(:embedded_signing)
    end
  end

  describe 'test attribute "embedded_signing_notifications"' do
    it 'should work' do
      expect(instance).to respond_to(:embedded_signing_notifications)
    end
  end

  describe 'test attribute "text_tags"' do
    it 'should work' do
      expect(instance).to respond_to(:text_tags)
    end
  end

  describe 'test attribute "custom_requester_name"' do
    it 'should work' do
      expect(instance).to respond_to(:custom_requester_name)
    end
  end

  describe 'test attribute "custom_requester_email"' do
    it 'should work' do
      expect(instance).to respond_to(:custom_requester_email)
    end
  end

  describe 'test attribute "redirect_url"' do
    it 'should work' do
      expect(instance).to respond_to(:redirect_url)
    end
  end

  describe 'test attribute "allow_decline"' do
    it 'should work' do
      expect(instance).to respond_to(:allow_decline)
    end
  end

  describe 'test attribute "allow_reassign"' do
    it 'should work' do
      expect(instance).to respond_to(:allow_reassign)
    end
  end

  describe 'test attribute "decline_redirect_url"' do
    it 'should work' do
      expect(instance).to respond_to(:decline_redirect_url)
    end
  end

  describe 'test attribute "language"' do
    it 'should work' do
      expect(instance).to respond_to(:language)
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      expect(instance).to respond_to(:metadata)
    end
  end

  describe 'test attribute "template_fields"' do
    it 'should work' do
      expect(instance).to respond_to(:template_fields)
    end
  end

  describe 'test attribute "files"' do
    it 'should work' do
      expect(instance).to respond_to(:files)
    end
  end

  describe 'test attribute "fields"' do
    it 'should work' do
      expect(instance).to respond_to(:fields)
    end
  end

  describe 'test attribute "attachment_requests"' do
    it 'should work' do
      expect(instance).to respond_to(:attachment_requests)
    end
  end

  describe 'test attribute "copied_contacts"' do
    it 'should work' do
      expect(instance).to respond_to(:copied_contacts)
    end
  end

  describe 'test attribute "labels"' do
    it 'should work' do
      expect(instance).to respond_to(:labels)
    end
  end

  describe 'test attribute "checkbox_groups"' do
    it 'should work' do
      expect(instance).to respond_to(:checkbox_groups)
    end
  end
end
