# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::DocumentListResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::DocumentListResponse do
  let(:instance) { SignWell::Models::DocumentListResponse.allocate }

  describe 'test an instance of DocumentListResponse' do
    it 'should create an instance of DocumentListResponse' do
      expect(instance).to be_a(SignWell::Models::DocumentListResponse)
    end
  end

  describe 'test attribute "documents"' do
    it 'should work' do
      expect(instance).to respond_to(:documents)
    end
  end

  describe 'test attribute "current_page"' do
    it 'should work' do
      expect(instance).to respond_to(:current_page)
    end
  end

  describe 'test attribute "next_page"' do
    it 'should work' do
      expect(instance).to respond_to(:next_page)
    end
  end

  describe 'test attribute "previous_page"' do
    it 'should work' do
      expect(instance).to respond_to(:previous_page)
    end
  end

  describe 'test attribute "total_count"' do
    it 'should work' do
      expect(instance).to respond_to(:total_count)
    end
  end

  describe 'test attribute "total_pages"' do
    it 'should work' do
      expect(instance).to respond_to(:total_pages)
    end
  end
end
