# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::ErrorResponseMeta
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::ErrorResponseMeta do
  let(:instance) { SignWell::Models::ErrorResponseMeta.allocate }

  describe 'test an instance of ErrorResponseMeta' do
    it 'should create an instance of ErrorResponseMeta' do
      expect(instance).to be_a(SignWell::Models::ErrorResponseMeta)
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      expect(instance).to respond_to(:error)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "messages"' do
    it 'should work' do
      expect(instance).to respond_to(:messages)
    end
  end
end
