# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::ErrorResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::ErrorResponse do
  let(:instance) { SignWell::Models::ErrorResponse.allocate }

  describe 'test an instance of ErrorResponse' do
    it 'should create an instance of ErrorResponse' do
      expect(instance).to be_a(SignWell::Models::ErrorResponse)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "meta"' do
    it 'should work' do
      expect(instance).to respond_to(:meta)
    end
  end
end
