# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::FieldType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::FieldType do
  let(:instance) { SignWell::Models::FieldType.new }

  describe 'test an instance of FieldType' do
    it 'should create an instance of FieldType' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SignWell::Models::FieldType)
    end
  end
end
