# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::FileInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::FileInfo do
  let(:instance) { SignWell::Models::FileInfo.allocate }

  describe 'test an instance of FileInfo' do
    it 'should create an instance of FileInfo' do
      expect(instance).to be_a(SignWell::Models::FileInfo)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "pages_number"' do
    it 'should work' do
      expect(instance).to respond_to(:pages_number)
    end
  end
end
