# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::FilesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::FilesInner do
  let(:instance) { SignWell::Models::FilesInner.allocate }

  describe 'test an instance of FilesInner' do
    it 'should create an instance of FilesInner' do
      expect(instance).to be_a(SignWell::Models::FilesInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "file_url"' do
    it 'should work' do
      expect(instance).to respond_to(:file_url)
    end
  end

  describe 'test attribute "file_base64"' do
    it 'should work' do
      expect(instance).to respond_to(:file_base64)
    end
  end
end
