# frozen_string_literal: true

# #SignWell Developer API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::FileFormat
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::FileFormat do
  let(:instance) { SignWell::FileFormat.new }

  describe 'test an instance of FileFormat' do
    it 'should create an instance of FileFormat' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SignWell::FileFormat)
    end
  end
end
