# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::MeResponseAccount
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::MeResponseAccount do
  let(:instance) { SignWell::Models::MeResponseAccount.allocate }

  describe 'test an instance of MeResponseAccount' do
    it 'should create an instance of MeResponseAccount' do
      expect(instance).to be_a(SignWell::Models::MeResponseAccount)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance).to respond_to(:id)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "plan_tier"' do
    it 'should work' do
      expect(instance).to respond_to(:plan_tier)
    end
  end

  describe 'test attribute "active_templates"' do
    it 'should work' do
      expect(instance).to respond_to(:active_templates)
    end
  end

  describe 'test attribute "can_create_template"' do
    it 'should work' do
      expect(instance).to respond_to(:can_create_template)
    end
  end

  describe 'test attribute "can_create_tracking_document"' do
    it 'should work' do
      expect(instance).to respond_to(:can_create_tracking_document)
    end
  end

  describe 'test attribute "can_create_completion_document"' do
    it 'should work' do
      expect(instance).to respond_to(:can_create_completion_document)
    end
  end

  describe 'test attribute "active_users"' do
    it 'should work' do
      expect(instance).to respond_to(:active_users)
    end
  end
end
