# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::MeResponseUserPreferences
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::MeResponseUserPreferences do
  let(:instance) { SignWell::Models::MeResponseUserPreferences.allocate }

  describe 'test an instance of MeResponseUserPreferences' do
    it 'should create an instance of MeResponseUserPreferences' do
      expect(instance).to be_a(SignWell::Models::MeResponseUserPreferences)
    end
  end

  describe 'test attribute "sales_document"' do
    it 'should work' do
      expect(instance).to respond_to(:sales_document)
    end
  end

  describe 'test attribute "time_zone"' do
    it 'should work' do
      expect(instance).to respond_to(:time_zone)
    end
  end

  describe 'test attribute "smart_fields"' do
    it 'should work' do
      expect(instance).to respond_to(:smart_fields)
    end
  end
end
