# frozen_string_literal: true

# #SignWell Developer API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Nom151CertificateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Nom151CertificateResponse do
  let(:instance) { SignWell::Nom151CertificateResponse.new }

  describe 'test an instance of Nom151CertificateResponse' do
    it 'should create an instance of Nom151CertificateResponse' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SignWell::Nom151CertificateResponse)
    end
  end

  describe 'test attribute "nom151"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
