# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::Nom151CertificateResponseNom151
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::Nom151CertificateResponseNom151 do
  let(:instance) { SignWell::Models::Nom151CertificateResponseNom151.allocate }

  describe 'test an instance of Nom151CertificateResponseNom151' do
    it 'should create an instance of Nom151CertificateResponseNom151' do
      expect(instance).to be_a(SignWell::Models::Nom151CertificateResponseNom151)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      expect(instance).to respond_to(:status)
    end
  end

  describe 'test attribute "transaction_id"' do
    it 'should work' do
      expect(instance).to respond_to(:transaction_id)
    end
  end

  describe 'test attribute "hash"' do
    it 'should work' do
      expect(instance).to respond_to(:hash)
    end
  end

  describe 'test attribute "folio"' do
    it 'should work' do
      expect(instance).to respond_to(:folio)
    end
  end

  describe 'test attribute "issued_at"' do
    it 'should work' do
      expect(instance).to respond_to(:issued_at)
    end
  end

  describe 'test attribute "provider"' do
    it 'should work' do
      expect(instance).to respond_to(:provider)
    end
  end

  describe 'test attribute "validation_url"' do
    it 'should work' do
      expect(instance).to respond_to(:validation_url)
    end
  end

  describe 'test attribute "constancia"' do
    it 'should work' do
      expect(instance).to respond_to(:constancia)
    end
  end
end
