# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::TemplateCheckboxGroupsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::TemplateCheckboxGroupsInner do
  let(:instance) { SignWell::Models::TemplateCheckboxGroupsInner.allocate }

  describe 'test an instance of TemplateCheckboxGroupsInner' do
    it 'should create an instance of TemplateCheckboxGroupsInner' do
      expect(instance).to be_a(SignWell::Models::TemplateCheckboxGroupsInner)
    end
  end

  describe 'test attribute "group_name"' do
    it 'should work' do
      expect(instance).to respond_to(:group_name)
    end
  end

  describe 'test attribute "placeholder_id"' do
    it 'should work' do
      expect(instance).to respond_to(:placeholder_id)
    end
  end

  describe 'test attribute "checkbox_ids"' do
    it 'should work' do
      expect(instance).to respond_to(:checkbox_ids)
    end
  end

  describe 'test attribute "validation"' do
    it 'should work' do
      expect(instance).to respond_to(:validation)
    end
  end

  describe 'test attribute "required"' do
    it 'should work' do
      expect(instance).to respond_to(:required)
    end
  end

  describe 'test attribute "min_value"' do
    it 'should work' do
      expect(instance).to respond_to(:min_value)
    end
  end

  describe 'test attribute "max_value"' do
    it 'should work' do
      expect(instance).to respond_to(:max_value)
    end
  end

  describe 'test attribute "exact_value"' do
    it 'should work' do
      expect(instance).to respond_to(:exact_value)
    end
  end
end
