# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::TextValidation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::TextValidation do
  let(:instance) { SignWell::Models::TextValidation.allocate }

  describe 'test an instance of TextValidation' do
    it 'should create an instance of TextValidation' do
      expect(instance).to be_a(SignWell::Models::TextValidation)
    end
  end
end
