# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SignWell::Models::UpdateRecipientsMapInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SignWell::Models::UpdateRecipientsMapInner do
  let(:instance) { SignWell::Models::UpdateRecipientsMapInner.allocate }

  describe 'test an instance of UpdateRecipientsMapInner' do
    it 'should create an instance of UpdateRecipientsMapInner' do
      expect(instance).to be_a(SignWell::Models::UpdateRecipientsMapInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance).to respond_to(:id)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance).to respond_to(:name)
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      expect(instance).to respond_to(:email)
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      expect(instance).to respond_to(:subject)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      expect(instance).to respond_to(:message)
    end
  end

  describe 'test attribute "passcode"' do
    it 'should work' do
      expect(instance).to respond_to(:passcode)
    end
  end
end
