# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "signwell_sdk/version"
require_relative "signwell_sdk/internal/util"
require_relative "signwell_sdk/internal/type/converter"
require_relative "signwell_sdk/internal/type/unknown"
require_relative "signwell_sdk/internal/type/boolean"
require_relative "signwell_sdk/internal/type/file_input"
require_relative "signwell_sdk/internal/type/enum"
require_relative "signwell_sdk/internal/type/union"
require_relative "signwell_sdk/internal/type/array_of"
require_relative "signwell_sdk/internal/type/hash_of"
require_relative "signwell_sdk/internal/type/base_model"
require_relative "signwell_sdk/internal/type/base_page"
require_relative "signwell_sdk/internal/type/request_parameters"
require_relative "signwell_sdk/internal"
require_relative "signwell_sdk/request_options"
require_relative "signwell_sdk/file_part"
require_relative "signwell_sdk/errors"
require_relative "signwell_sdk/internal/transport/base_client"
require_relative "signwell_sdk/internal/transport/pooled_net_requester"
require_relative "signwell_sdk/client"
require_relative "signwell_sdk/models/v1/api_application_delete_params"
require_relative "signwell_sdk/models/v1/api_application_retrieve_params"
require_relative "signwell_sdk/models/v1/attachment_request"
require_relative "signwell_sdk/models/v1/bulk_send_create_params"
require_relative "signwell_sdk/models/v1/bulk_send_list_params"
require_relative "signwell_sdk/models/v1/bulk_send_retrieve_csv_template_params"
require_relative "signwell_sdk/models/v1/bulk_send_retrieve_documents_params"
require_relative "signwell_sdk/models/v1/bulk_send_retrieve_params"
require_relative "signwell_sdk/models/v1/bulk_send_validate_csv_params"
require_relative "signwell_sdk/models/v1/checkbox_group"
require_relative "signwell_sdk/models/v1/copied_contact"
require_relative "signwell_sdk/models/v1/document"
require_relative "signwell_sdk/models/v1/document_create_from_template_params"
require_relative "signwell_sdk/models/v1/document_create_from_template_response"
require_relative "signwell_sdk/models/v1/document_create_params"
require_relative "signwell_sdk/models/v1/document_delete_params"
require_relative "signwell_sdk/models/v1/document_file"
require_relative "signwell_sdk/models/v1/document_list_params"
require_relative "signwell_sdk/models/v1/document_list_response"
require_relative "signwell_sdk/models/v1/document_remind_params"
require_relative "signwell_sdk/models/v1/document_retrieve_completed_pdf_params"
require_relative "signwell_sdk/models/v1/document_retrieve_completed_pdf_response"
require_relative "signwell_sdk/models/v1/document_retrieve_nom151_certificate_params"
require_relative "signwell_sdk/models/v1/document_retrieve_nom151_certificate_response"
require_relative "signwell_sdk/models/v1/document_retrieve_params"
require_relative "signwell_sdk/models/v1/document_send_params"
require_relative "signwell_sdk/models/v1/document_template"
require_relative "signwell_sdk/models/v1/document_template_create_params"
require_relative "signwell_sdk/models/v1/document_template_delete_params"
require_relative "signwell_sdk/models/v1/document_template_list_params"
require_relative "signwell_sdk/models/v1/document_template_list_response"
require_relative "signwell_sdk/models/v1/document_template_retrieve_params"
require_relative "signwell_sdk/models/v1/document_template_update_params"
require_relative "signwell_sdk/models/v1/hook_create_params"
require_relative "signwell_sdk/models/v1/hook_delete_params"
require_relative "signwell_sdk/models/v1/hook_list_params"
require_relative "signwell_sdk/models/v1/label"
require_relative "signwell_sdk/models/v1/template_checkbox_group"
require_relative "signwell_sdk/models/v1_me_params"
require_relative "signwell_sdk/models"
require_relative "signwell_sdk/resources/v1"
require_relative "signwell_sdk/resources/v1/api_applications"
require_relative "signwell_sdk/resources/v1/bulk_sends"
require_relative "signwell_sdk/resources/v1/documents"
require_relative "signwell_sdk/resources/v1/document_templates"
require_relative "signwell_sdk/resources/v1/hooks"
