=begin
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
  module Models
    class AccountInfoResponsePreferences
      # @return [String]
      attr_accessor :date_format

      # @return [Integer]
      attr_accessor :days_until_links_expire

      # @return [Boolean]
      attr_accessor :disable_apply_everywhere

      # @return [Boolean]
      attr_accessor :disable_apply_everywhere_effective

      # @return [Boolean]
      attr_accessor :disable_drawn_signatures

      # @return [Boolean]
      attr_accessor :disable_typed_signatures

      # @return [Boolean]
      attr_accessor :disable_uploaded_signatures

      # @return [Boolean]
      attr_accessor :enable_redirect

      # @return [Boolean]
      attr_accessor :hide_document_id_in_audit

      # @return [Boolean]
      attr_accessor :mute_branding

      # @return [String]
      attr_accessor :redirect_url

      # @return [Boolean]
      attr_accessor :separate_audit_pdf

      # @return [Boolean]
      attr_accessor :separate_completed_file

      # @return [Boolean]
      attr_accessor :enable_nom151_compliance

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          :'date_format' => :'date_format',
          :'days_until_links_expire' => :'days_until_links_expire',
          :'disable_apply_everywhere' => :'disable_apply_everywhere',
          :'disable_apply_everywhere_effective' => :'disable_apply_everywhere_effective',
          :'disable_drawn_signatures' => :'disable_drawn_signatures',
          :'disable_typed_signatures' => :'disable_typed_signatures',
          :'disable_uploaded_signatures' => :'disable_uploaded_signatures',
          :'enable_redirect' => :'enable_redirect',
          :'hide_document_id_in_audit' => :'hide_document_id_in_audit',
          :'mute_branding' => :'mute_branding',
          :'redirect_url' => :'redirect_url',
          :'separate_audit_pdf' => :'separate_audit_pdf',
          :'separate_completed_file' => :'separate_completed_file',
          :'enable_nom151_compliance' => :'enable_nom151_compliance'
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          :'date_format' => :'String',
          :'days_until_links_expire' => :'Integer',
          :'disable_apply_everywhere' => :'Boolean',
          :'disable_apply_everywhere_effective' => :'Boolean',
          :'disable_drawn_signatures' => :'Boolean',
          :'disable_typed_signatures' => :'Boolean',
          :'disable_uploaded_signatures' => :'Boolean',
          :'enable_redirect' => :'Boolean',
          :'hide_document_id_in_audit' => :'Boolean',
          :'mute_branding' => :'Boolean',
          :'redirect_url' => :'String',
          :'separate_audit_pdf' => :'Boolean',
          :'separate_completed_file' => :'Boolean',
          :'enable_nom151_compliance' => :'Boolean'
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new([
          :'redirect_url',
        ])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        if (!attributes.is_a?(Hash))
          fail ArgumentError, "The input argument (attributes) must be a hash in `SignWell::AccountInfoResponsePreferences` initialize method"
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) { |(k, v), h|
          if (!acceptable_attribute_map.key?(k.to_sym))
            fail ArgumentError, "`#{k}` is not a valid attribute in `SignWell::AccountInfoResponsePreferences`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end
          h[k.to_sym] = v
        }

        if attributes.key?(:'date_format')
          self.date_format = attributes[:'date_format']
        end

        if attributes.key?(:'days_until_links_expire')
          self.days_until_links_expire = attributes[:'days_until_links_expire']
        end

        if attributes.key?(:'disable_apply_everywhere')
          self.disable_apply_everywhere = attributes[:'disable_apply_everywhere']
        end

        if attributes.key?(:'disable_apply_everywhere_effective')
          self.disable_apply_everywhere_effective = attributes[:'disable_apply_everywhere_effective']
        end

        if attributes.key?(:'disable_drawn_signatures')
          self.disable_drawn_signatures = attributes[:'disable_drawn_signatures']
        end

        if attributes.key?(:'disable_typed_signatures')
          self.disable_typed_signatures = attributes[:'disable_typed_signatures']
        end

        if attributes.key?(:'disable_uploaded_signatures')
          self.disable_uploaded_signatures = attributes[:'disable_uploaded_signatures']
        end

        if attributes.key?(:'enable_redirect')
          self.enable_redirect = attributes[:'enable_redirect']
        end

        if attributes.key?(:'hide_document_id_in_audit')
          self.hide_document_id_in_audit = attributes[:'hide_document_id_in_audit']
        end

        if attributes.key?(:'mute_branding')
          self.mute_branding = attributes[:'mute_branding']
        end

        if attributes.key?(:'redirect_url')
          self.redirect_url = attributes[:'redirect_url']
        end

        if attributes.key?(:'separate_audit_pdf')
          self.separate_audit_pdf = attributes[:'separate_audit_pdf']
        end

        if attributes.key?(:'separate_completed_file')
          self.separate_completed_file = attributes[:'separate_completed_file']
        end

        if attributes.key?(:'enable_nom151_compliance')
          self.enable_nom151_compliance = attributes[:'enable_nom151_compliance']
        end
      end


      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = Array.new
        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        true
      end

      # Checks equality by comparing each attribute.
      # @param [Object] other Object to be compared
      def ==(o)
        return true if self.equal?(o)
        self.class == o.class &&
            date_format == o.date_format &&
            days_until_links_expire == o.days_until_links_expire &&
            disable_apply_everywhere == o.disable_apply_everywhere &&
            disable_apply_everywhere_effective == o.disable_apply_everywhere_effective &&
            disable_drawn_signatures == o.disable_drawn_signatures &&
            disable_typed_signatures == o.disable_typed_signatures &&
            disable_uploaded_signatures == o.disable_uploaded_signatures &&
            enable_redirect == o.enable_redirect &&
            hide_document_id_in_audit == o.hide_document_id_in_audit &&
            mute_branding == o.mute_branding &&
            redirect_url == o.redirect_url &&
            separate_audit_pdf == o.separate_audit_pdf &&
            separate_completed_file == o.separate_completed_file &&
            enable_nom151_compliance == o.enable_nom151_compliance
      end

      # @see the `==` method
      # @param [Object] other Object to be compared
      def eql?(o)
        self == o
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [date_format, days_until_links_expire, disable_apply_everywhere, disable_apply_everywhere_effective, disable_drawn_signatures, disable_typed_signatures, disable_uploaded_signatures, enable_redirect, hide_document_id_in_audit, mute_branding, redirect_url, separate_audit_pdf, separate_completed_file, enable_nom151_compliance].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)
        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash["#{key}"] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param [String] type Data type
      # @param [String] value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        normalize_for_serialization! if respond_to?(:normalize_for_serialization!, true)

        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = self.send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
