# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class AdditionalFieldsInnerInner
      # Horizontal value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located.
      attr_accessor :x

      # Vertical value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located.
      attr_accessor :y

      # The page number within the file. If the page does not exist within the file then the field won't be created.
      attr_accessor :page

      # Unique identifier of the recipient assigned to the field. Recipients assigned to fields will be the only ones that will see and be able to complete those fields.
      attr_accessor :recipient_id

      attr_accessor :type, :value, :validation, :date_format

      # Whether the field must be completed by the recipient. Defaults to `true` except for checkbox type fields.
      attr_accessor :required

      # Text and Date fields only: label that is displayed when the field is empty.
      attr_accessor :label

      # Unique identifier of the field. Useful when needing to reference specific field values or update a document and its fields.
      attr_accessor :api_id

      # Checkbox fields only. At least 2 checkbox fields in an array of fields must be assigned to the same recipient and grouped with selection requirements.
      attr_accessor :name

      # Text fields only: whether the field width will stay fixed and text will display in multiple lines, rather than one long line. If set to `false` the field width will automatically grow horizontally to fit text on one line. Defaults to `false`.
      attr_accessor :fixed_width

      # Date fields only: makes fields readonly and automatically populates with the date the recipient signed. Defaults to `false`.
      attr_accessor :lock_sign_date

      # Date fields only (text field formulas coming soon): formulas are a way to prefill fields with calculated future or past dates. Addition, subtraction, and parentheses are allowed. Valid event dates are `created_date`, `sent_date`, and `signed_date`. Valid time periods are `day`, `days`, `week`, `weeks`, `month`, and `months`. Example: `formula: 'sent_date + 10 days'`. Use with `lock_sign_date` if you'd like to make the field readonly and prevent signers from choosing a different date.
      attr_accessor :formula

      # Height of the field (in pixels). Maximum height varies by field type: Signature/Initials (200px), others (74px). When using text tags if the height is greater than the maximum height, the height will be set to the maximum height.
      attr_accessor :height

      # Width of the field (in pixels). For text fields, width will auto-grow unless `fixed_width` is true.
      attr_accessor :width

      # Array of dropdown options (for dropdown/select fields only)
      attr_accessor :options

      # Default selected option (for dropdown/select fields only)
      attr_accessor :default_option

      # Whether to allow \"Other\" option with text input (for dropdown/select fields only)
      attr_accessor :allow_other

      class EnumAttributeValidator
        attr_reader :datatype, :allowable_values

        def initialize(datatype, allowable_values)
          @allowable_values = allowable_values.map do |value|
            case datatype.to_s
            when /Integer/i
              value.to_i
            when /Float/i
              value.to_f
            else
              value
            end
          end
        end

        def valid?(value)
          !value || allowable_values.include?(value)
        end
      end

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          'x': :x,
          'y': :y,
          'page': :page,
          'recipient_id': :recipient_id,
          'type': :type,
          'required': :required,
          'label': :label,
          'value': :value,
          'api_id': :api_id,
          'name': :name,
          'validation': :validation,
          'fixed_width': :fixed_width,
          'lock_sign_date': :lock_sign_date,
          'date_format': :date_format,
          'formula': :formula,
          'height': :height,
          'width': :width,
          'options': :options,
          'default_option': :default_option,
          'allow_other': :allow_other
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          'x': :Float,
          'y': :Float,
          'page': :Integer,
          'recipient_id': :String,
          'type': :FieldType,
          'required': :Boolean,
          'label': :String,
          'value': :AdditionalFieldsInnerInnerValue,
          'api_id': :String,
          'name': :String,
          'validation': :TextValidation,
          'fixed_width': :Boolean,
          'lock_sign_date': :Boolean,
          'date_format': :DateFormat,
          'formula': :String,
          'height': :Float,
          'width': :Float,
          'options': :'Array<DropdownOption>',
          'default_option': :String,
          'allow_other': :Boolean
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new([])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        unless attributes.is_a?(Hash)
          raise ArgumentError,
                'The input argument (attributes) must be a hash in `SignWell::AdditionalFieldsInnerInner` initialize method'
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) do |(k, v), h|
          unless acceptable_attribute_map.key?(k.to_sym)
            raise ArgumentError,
                  "`#{k}` is not a valid attribute in `SignWell::AdditionalFieldsInnerInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end

          h[k.to_sym] = v
        end

        self.x = (attributes[:x] if attributes.key?(:x))

        self.y = (attributes[:y] if attributes.key?(:y))

        self.page = (attributes[:page] if attributes.key?(:page))

        self.recipient_id = (attributes[:recipient_id] if attributes.key?(:recipient_id))

        self.type = (attributes[:type] if attributes.key?(:type))

        self.required = if attributes.key?(:required)
                          attributes[:required]
                        else
                          true
                        end

        self.label = attributes[:label] if attributes.key?(:label)

        self.value = attributes[:value] if attributes.key?(:value)

        self.api_id = attributes[:api_id] if attributes.key?(:api_id)

        self.name = attributes[:name] if attributes.key?(:name)

        self.validation = attributes[:validation] if attributes.key?(:validation)

        self.fixed_width = if attributes.key?(:fixed_width)
                             attributes[:fixed_width]
                           else
                             false
                           end

        self.lock_sign_date = if attributes.key?(:lock_sign_date)
                                attributes[:lock_sign_date]
                              else
                                false
                              end

        self.date_format = attributes[:date_format] if attributes.key?(:date_format)

        self.formula = attributes[:formula] if attributes.key?(:formula)

        self.height = attributes[:height] if attributes.key?(:height)

        self.width = attributes[:width] if attributes.key?(:width)

        if attributes.key?(:options) && (value = attributes[:options]).is_a?(Array)
          self.options = value
        end

        self.default_option = attributes[:default_option] if attributes.key?(:default_option)

        self.allow_other = if attributes.key?(:allow_other)
                             attributes[:allow_other]
                           else
                             false
                           end
      end

      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = []
        invalid_properties.push('invalid value for "x", x cannot be nil.') if @x.nil?

        invalid_properties.push('invalid value for "y", y cannot be nil.') if @y.nil?

        invalid_properties.push('invalid value for "page", page cannot be nil.') if @page.nil?

        invalid_properties.push('invalid value for "recipient_id", recipient_id cannot be nil.') if @recipient_id.nil?

        invalid_properties.push('invalid value for "type", type cannot be nil.') if @type.nil?

        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        return false if @x.nil?
        return false if @y.nil?
        return false if @page.nil?
        return false if @recipient_id.nil?
        return false if @type.nil?

        true
      end

      # Custom attribute writer method with validation
      # @param [Object] x Value to be assigned
      def x=(x)
        raise ArgumentError, 'x cannot be nil' if x.nil?

        @x = x
      end

      # Custom attribute writer method with validation
      # @param [Object] y Value to be assigned
      def y=(y)
        raise ArgumentError, 'y cannot be nil' if y.nil?

        @y = y
      end

      # Custom attribute writer method with validation
      # @param [Object] page Value to be assigned
      def page=(page)
        raise ArgumentError, 'page cannot be nil' if page.nil?

        @page = page
      end

      # Custom attribute writer method with validation
      # @param [Object] recipient_id Value to be assigned
      def recipient_id=(recipient_id)
        raise ArgumentError, 'recipient_id cannot be nil' if recipient_id.nil?

        @recipient_id = recipient_id
      end

      # Custom attribute writer method with validation
      # @param [Object] type Value to be assigned
      def type=(type)
        raise ArgumentError, 'type cannot be nil' if type.nil?

        @type = type
      end

      # Checks equality by comparing each attribute.
      # @param [Object] Object to be compared
      def ==(other)
        return true if equal?(other)

        self.class == other.class &&
          x == other.x &&
          y == other.y &&
          page == other.page &&
          recipient_id == other.recipient_id &&
          type == other.type &&
          required == other.required &&
          label == other.label &&
          value == other.value &&
          api_id == other.api_id &&
          name == other.name &&
          validation == other.validation &&
          fixed_width == other.fixed_width &&
          lock_sign_date == other.lock_sign_date &&
          date_format == other.date_format &&
          formula == other.formula &&
          height == other.height &&
          width == other.width &&
          options == other.options &&
          default_option == other.default_option &&
          allow_other == other.allow_other
      end

      # @see the `==` method
      # @param [Object] Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [x, y, page, recipient_id, type, required, label, value, api_id, name, validation, fixed_width, lock_sign_date,
         date_format, formula, height, width, options, default_option, allow_other].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)

        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_s] = attributes[attribute_map[key]].map do |v|
                _deserialize(::Regexp.last_match(1), v)
              end
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param string type Data type
      # @param string value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
