# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class ApiApplicationResponsePreferences
      # @return [String]
      attr_accessor :button_text_color

      # @return [Integer]
      attr_accessor :buttons_border_radius

      # @return [String]
      attr_accessor :custom_logo_file

      # @return [String]
      attr_accessor :link_text_color

      # @return [String]
      attr_accessor :primary_color

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          'button_text_color': :button_text_color,
          'buttons_border_radius': :buttons_border_radius,
          'custom_logo_file': :custom_logo_file,
          'link_text_color': :link_text_color,
          'primary_color': :primary_color
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          'button_text_color': :String,
          'buttons_border_radius': :Integer,
          'custom_logo_file': :String,
          'link_text_color': :String,
          'primary_color': :String
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new(%i[
                  button_text_color
                  custom_logo_file
                  link_text_color
                  primary_color
                ])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        unless attributes.is_a?(Hash)
          raise ArgumentError,
                'The input argument (attributes) must be a hash in `SignWell::ApiApplicationResponsePreferences` initialize method'
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) do |(k, v), h|
          unless acceptable_attribute_map.key?(k.to_sym)
            raise ArgumentError,
                  "`#{k}` is not a valid attribute in `SignWell::ApiApplicationResponsePreferences`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end

          h[k.to_sym] = v
        end

        self.button_text_color = attributes[:button_text_color] if attributes.key?(:button_text_color)

        self.buttons_border_radius = attributes[:buttons_border_radius] if attributes.key?(:buttons_border_radius)

        self.custom_logo_file = attributes[:custom_logo_file] if attributes.key?(:custom_logo_file)

        self.link_text_color = attributes[:link_text_color] if attributes.key?(:link_text_color)

        return unless attributes.key?(:primary_color)

        self.primary_color = attributes[:primary_color]
      end

      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        []
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        true
      end

      # Checks equality by comparing each attribute.
      # @param [Object] other Object to be compared
      def ==(other)
        return true if equal?(other)

        self.class == other.class &&
          button_text_color == other.button_text_color &&
          buttons_border_radius == other.buttons_border_radius &&
          custom_logo_file == other.custom_logo_file &&
          link_text_color == other.link_text_color &&
          primary_color == other.primary_color
      end

      # @see the `==` method
      # @param [Object] other Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [button_text_color, buttons_border_radius, custom_logo_file, link_text_color, primary_color].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)

        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_s] = attributes[attribute_map[key]].map do |v|
                _deserialize(::Regexp.last_match(1), v)
              end
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param [String] type Data type
      # @param [String] value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
