# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class CheckboxGroupsInner
      # A unique identifier for the checkbox group.
      attr_accessor :group_name

      # The recipient ID associated with the checkbox group.
      attr_accessor :recipient_id

      attr_accessor :checkbox_ids, :validation

      # Whether the group must be completed by the recipient. Defaults to false.
      attr_accessor :required

      # The minimum number of checkboxes that must be checked in the group. (Only for validation: minimum and range)
      attr_accessor :min_value

      # The maximum number of checkboxes that can be checked in the group. (Only for validation: maximum and range)
      attr_accessor :max_value

      # The exact number of checkboxes that must be checked in the group. (Only for validation: exact)
      attr_accessor :exact_value

      class EnumAttributeValidator
        attr_reader :datatype, :allowable_values

        def initialize(datatype, allowable_values)
          @allowable_values = allowable_values.map do |value|
            case datatype.to_s
            when /Integer/i
              value.to_i
            when /Float/i
              value.to_f
            else
              value
            end
          end
        end

        def valid?(value)
          !value || allowable_values.include?(value)
        end
      end

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          'group_name': :group_name,
          'recipient_id': :recipient_id,
          'checkbox_ids': :checkbox_ids,
          'validation': :validation,
          'required': :required,
          'min_value': :min_value,
          'max_value': :max_value,
          'exact_value': :exact_value
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          'group_name': :String,
          'recipient_id': :String,
          'checkbox_ids': :'Array<String>',
          'validation': :CheckboxValidation,
          'required': :Boolean,
          'min_value': :Integer,
          'max_value': :Integer,
          'exact_value': :Integer
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new([])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        unless attributes.is_a?(Hash)
          raise ArgumentError,
                'The input argument (attributes) must be a hash in `SignWell::CheckboxGroupsInner` initialize method'
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) do |(k, v), h|
          unless acceptable_attribute_map.key?(k.to_sym)
            raise ArgumentError,
                  "`#{k}` is not a valid attribute in `SignWell::CheckboxGroupsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end

          h[k.to_sym] = v
        end

        self.group_name = (attributes[:group_name] if attributes.key?(:group_name))

        self.recipient_id = (attributes[:recipient_id] if attributes.key?(:recipient_id))

        if attributes.key?(:checkbox_ids)
          if (value = attributes[:checkbox_ids]).is_a?(Array)
            self.checkbox_ids = value
          end
        else
          self.checkbox_ids = nil
        end

        self.validation = attributes[:validation] if attributes.key?(:validation)

        self.required = if attributes.key?(:required)
                          attributes[:required]
                        else
                          false
                        end

        self.min_value = attributes[:min_value] if attributes.key?(:min_value)

        self.max_value = attributes[:max_value] if attributes.key?(:max_value)

        return unless attributes.key?(:exact_value)

        self.exact_value = attributes[:exact_value]
      end

      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = []
        invalid_properties.push('invalid value for "group_name", group_name cannot be nil.') if @group_name.nil?

        invalid_properties.push('invalid value for "recipient_id", recipient_id cannot be nil.') if @recipient_id.nil?

        invalid_properties.push('invalid value for "checkbox_ids", checkbox_ids cannot be nil.') if @checkbox_ids.nil?

        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        return false if @group_name.nil?
        return false if @recipient_id.nil?
        return false if @checkbox_ids.nil?

        true
      end

      # Custom attribute writer method with validation
      # @param [Object] group_name Value to be assigned
      def group_name=(group_name)
        raise ArgumentError, 'group_name cannot be nil' if group_name.nil?

        @group_name = group_name
      end

      # Custom attribute writer method with validation
      # @param [Object] recipient_id Value to be assigned
      def recipient_id=(recipient_id)
        raise ArgumentError, 'recipient_id cannot be nil' if recipient_id.nil?

        @recipient_id = recipient_id
      end

      # Custom attribute writer method with validation
      # @param [Object] checkbox_ids Value to be assigned
      def checkbox_ids=(checkbox_ids)
        raise ArgumentError, 'checkbox_ids cannot be nil' if checkbox_ids.nil?

        @checkbox_ids = checkbox_ids
      end

      # Checks equality by comparing each attribute.
      # @param [Object] Object to be compared
      def ==(other)
        return true if equal?(other)

        self.class == other.class &&
          group_name == other.group_name &&
          recipient_id == other.recipient_id &&
          checkbox_ids == other.checkbox_ids &&
          validation == other.validation &&
          required == other.required &&
          min_value == other.min_value &&
          max_value == other.max_value &&
          exact_value == other.exact_value
      end

      # @see the `==` method
      # @param [Object] Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [group_name, recipient_id, checkbox_ids, validation, required, min_value, max_value, exact_value].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)

        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_s] = attributes[attribute_map[key]].map do |v|
                _deserialize(::Regexp.last_match(1), v)
              end
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param string type Data type
      # @param string value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
