=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
module Models
  class DateFormat
    MM_DD_YYYY = "MM/DD/YYYY".freeze
    DD_MM_YYYY = "DD/MM/YYYY".freeze
    YYYY_MM_DD = "YYYY/MM/DD".freeze
    MONTH_DD_YYYY = "Month DD, YYYY".freeze
    MM_DD_YYYY_HH_MM_SS_A = "MM/DD/YYYY hh:mm:ss a".freeze

    def self.all_vars
      @all_vars ||= [MM_DD_YYYY, DD_MM_YYYY, YYYY_MM_DD, MONTH_DD_YYYY, MM_DD_YYYY_HH_MM_SS_A].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DateFormat.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DateFormat"
    end
  end
end
end
