# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class DocumentResponseFieldsInnerInner
      attr_accessor :x, :y, :page, :recipient, :api_id, :name, :date_format, :fixed_width, :label, :lock_sign_date,
                    :required, :type, :validation, :value, :height, :width, :recipient_id, :signing_elements_group_id, :placeholder_name

      # Dropdown options (for dropdown/select fields)
      attr_accessor :options

      # Default selected option
      attr_accessor :default_option

      # Whether \"Other\" option is allowed
      attr_accessor :allow_other

      class EnumAttributeValidator
        attr_reader :datatype, :allowable_values

        def initialize(datatype, allowable_values)
          @allowable_values = allowable_values.map do |value|
            case datatype.to_s
            when /Integer/i
              value.to_i
            when /Float/i
              value.to_f
            else
              value
            end
          end
        end

        def valid?(value)
          !value || allowable_values.include?(value)
        end
      end

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          'x': :x,
          'y': :y,
          'page': :page,
          'recipient': :recipient,
          'api_id': :api_id,
          'name': :name,
          'date_format': :date_format,
          'fixed_width': :fixed_width,
          'label': :label,
          'lock_sign_date': :lock_sign_date,
          'required': :required,
          'type': :type,
          'validation': :validation,
          'value': :value,
          'height': :height,
          'width': :width,
          'recipient_id': :recipient_id,
          'signing_elements_group_id': :signing_elements_group_id,
          'placeholder_name': :placeholder_name,
          'options': :options,
          'default_option': :default_option,
          'allow_other': :allow_other
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          'x': :Float,
          'y': :Float,
          'page': :Integer,
          'recipient': :DocumentResponseFieldsInnerInnerRecipient,
          'api_id': :String,
          'name': :String,
          'date_format': :DateFormat,
          'fixed_width': :Boolean,
          'label': :String,
          'lock_sign_date': :Boolean,
          'required': :Boolean,
          'type': :FieldType,
          'validation': :TextValidation,
          'value': :DocumentResponseFieldsInnerInnerValue,
          'height': :String,
          'width': :String,
          'recipient_id': :String,
          'signing_elements_group_id': :String,
          'placeholder_name': :String,
          'options': :'Array<DocumentResponseFieldsInnerInnerOptionsInner>',
          'default_option': :String,
          'allow_other': :Boolean
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new(%i[
                  name
                  value
                  recipient_id
                ])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        unless attributes.is_a?(Hash)
          raise ArgumentError,
                'The input argument (attributes) must be a hash in `SignWell::DocumentResponseFieldsInnerInner` initialize method'
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) do |(k, v), h|
          unless acceptable_attribute_map.key?(k.to_sym)
            raise ArgumentError,
                  "`#{k}` is not a valid attribute in `SignWell::DocumentResponseFieldsInnerInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end

          h[k.to_sym] = v
        end

        self.x = (attributes[:x] if attributes.key?(:x))

        self.y = (attributes[:y] if attributes.key?(:y))

        self.page = (attributes[:page] if attributes.key?(:page))

        self.recipient = attributes[:recipient] if attributes.key?(:recipient)

        self.api_id = attributes[:api_id] if attributes.key?(:api_id)

        self.name = attributes[:name] if attributes.key?(:name)

        self.date_format = attributes[:date_format] if attributes.key?(:date_format)

        self.fixed_width = attributes[:fixed_width] if attributes.key?(:fixed_width)

        self.label = attributes[:label] if attributes.key?(:label)

        self.lock_sign_date = attributes[:lock_sign_date] if attributes.key?(:lock_sign_date)

        self.required = attributes[:required] if attributes.key?(:required)

        self.type = attributes[:type] if attributes.key?(:type)

        self.validation = attributes[:validation] if attributes.key?(:validation)

        self.value = attributes[:value] if attributes.key?(:value)

        self.height = attributes[:height] if attributes.key?(:height)

        self.width = attributes[:width] if attributes.key?(:width)

        self.recipient_id = attributes[:recipient_id] if attributes.key?(:recipient_id)

        if attributes.key?(:signing_elements_group_id)
          self.signing_elements_group_id = attributes[:signing_elements_group_id]
        end

        self.placeholder_name = attributes[:placeholder_name] if attributes.key?(:placeholder_name)

        if attributes.key?(:options) && (value = attributes[:options]).is_a?(Array)
          self.options = value
        end

        self.default_option = attributes[:default_option] if attributes.key?(:default_option)

        return unless attributes.key?(:allow_other)

        self.allow_other = attributes[:allow_other]
      end

      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = []
        invalid_properties.push('invalid value for "x", x cannot be nil.') if @x.nil?

        invalid_properties.push('invalid value for "y", y cannot be nil.') if @y.nil?

        invalid_properties.push('invalid value for "page", page cannot be nil.') if @page.nil?

        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        return false if @x.nil?
        return false if @y.nil?
        return false if @page.nil?

        true
      end

      # Custom attribute writer method with validation
      # @param [Object] x Value to be assigned
      def x=(x)
        raise ArgumentError, 'x cannot be nil' if x.nil?

        @x = x
      end

      # Custom attribute writer method with validation
      # @param [Object] y Value to be assigned
      def y=(y)
        raise ArgumentError, 'y cannot be nil' if y.nil?

        @y = y
      end

      # Custom attribute writer method with validation
      # @param [Object] page Value to be assigned
      def page=(page)
        raise ArgumentError, 'page cannot be nil' if page.nil?

        @page = page
      end

      # Checks equality by comparing each attribute.
      # @param [Object] Object to be compared
      def ==(other)
        return true if equal?(other)

        self.class == other.class &&
          x == other.x &&
          y == other.y &&
          page == other.page &&
          recipient == other.recipient &&
          api_id == other.api_id &&
          name == other.name &&
          date_format == other.date_format &&
          fixed_width == other.fixed_width &&
          label == other.label &&
          lock_sign_date == other.lock_sign_date &&
          required == other.required &&
          type == other.type &&
          validation == other.validation &&
          value == other.value &&
          height == other.height &&
          width == other.width &&
          recipient_id == other.recipient_id &&
          signing_elements_group_id == other.signing_elements_group_id &&
          placeholder_name == other.placeholder_name &&
          options == other.options &&
          default_option == other.default_option &&
          allow_other == other.allow_other
      end

      # @see the `==` method
      # @param [Object] Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [x, y, page, recipient, api_id, name, date_format, fixed_width, label, lock_sign_date, required, type,
         validation, value, height, width, recipient_id, signing_elements_group_id, placeholder_name, options, default_option, allow_other].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)

        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_s] = attributes[attribute_map[key]].map do |v|
                _deserialize(::Regexp.last_match(1), v)
              end
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param string type Data type
      # @param string value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
