=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
module Models
  class DocumentRequest
    # Set to `true` to enable Test Mode. Documents created with Test Mode do not count towards API billing and are not legally binding. Defaults to `false`
    attr_accessor :test_mode

    # Document files can be uploaded by specifying a file URL or base64 string. Either `file_url` or `file_base64` must be present (not both). Valid file types are: .pdf, .doc, .docx, .pages, .ppt, .pptx, .key, .xls, .xlsx, .numbers, .jpg, .jpeg, .png, .tiff, .tif, .webp, .html, and .htm
    attr_accessor :files

    # The name of the document.
    attr_accessor :name

    # Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).
    attr_accessor :subject

    # Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).
    attr_accessor :message

    # Document recipients are people that must complete and/or sign a document.
    attr_accessor :recipients

    # Whether the document can still be updated before sending a signature request. If set to `false` the document is sent for signing as part of this request. Defaults to `false`.
    attr_accessor :draft

    # When set to true the document will enter self-sign mode, which allows the document creator to sign and complete a document without any field setup. Must use the embedded_edit_url in the response and (if embedding) the embedded requesting workflow.
    attr_accessor :self_sign

    # When set to `true` the document will have a signature page added to the end, and all signers will be required to add their signature on that page.
    attr_accessor :with_signature_page

    # Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).
    attr_accessor :expires_in

    # Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.
    attr_accessor :reminders

    # When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.
    attr_accessor :apply_signing_order

    # Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
    attr_accessor :api_application_id

    # When set to `true` it enables embedded signing in your website/web application. Embedded functionality works with an iFrame and email authentication is disabled. :embedded_signinig defaults to `false`.
    attr_accessor :embedded_signing

    # On embedding signing, document owners (and CC'd contacts) do not get a notification email when documents have been completed. Setting this param to `true` will send out those final completed notifications. Default is `false`
    attr_accessor :embedded_signing_notifications

    # An alternative way (if you can’t use the recommended way) of placing fields in specific locations of your document by using special text tags. Useful when changing the content of your files changes the location of fields. See API documentation for “Text Tags” for details. Defaults to false.
    attr_accessor :text_tags

    # Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.
    attr_accessor :custom_requester_name

    # Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.
    attr_accessor :custom_requester_email

    # A URL that recipients are redirected to after successfully signing a document.
    attr_accessor :redirect_url

    # Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.
    attr_accessor :allow_decline

    # In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.
    attr_accessor :allow_reassign

    # A URL that recipients are redirected to if the document is declined.
    attr_accessor :decline_redirect_url

    # Sets the language for all recipients on the document and updates all recipient side interactions including the document email and the document itself. Accepted languages: English, Français, Español, Deutsch, Polski, Português, Dansk, Nederlands, Italiano, Русский, Svenska, العربية, Ελληνικά, Türkçe, Slovenčina. Defaults to English. Language should be sent in ISO 639-1 format: en, fr, es, de, pl, pt, da, nl, it, ru, sv, ar, el, tr, sk.
    attr_accessor :language

    # Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.
    attr_accessor :metadata

    # Document fields placed on a document for collecting data or signatures from recipients. At least one field must be present in the Create Document request if `draft` is `false` (unless adding a signature page by using `with_signature_page`). Field data should be sent as a 2-dimensional JSON array. One array of fields is needed for each file in the files array. An array of fields can be empty if you have a file that does not contain any fields.
    attr_accessor :fields

    # Attachments that a recipient must upload to complete the signing process. Attachment requests are shown after all document fields have been completed.
    attr_accessor :attachment_requests

    # Copied contacts are emailed the final document once it has been completed by all recipients.
    attr_accessor :copied_contacts

    # Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels.
    attr_accessor :labels

    # Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.
    attr_accessor :checkbox_groups

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'test_mode' => :'test_mode',
        :'files' => :'files',
        :'name' => :'name',
        :'subject' => :'subject',
        :'message' => :'message',
        :'recipients' => :'recipients',
        :'draft' => :'draft',
        :'self_sign' => :'self_sign',
        :'with_signature_page' => :'with_signature_page',
        :'expires_in' => :'expires_in',
        :'reminders' => :'reminders',
        :'apply_signing_order' => :'apply_signing_order',
        :'api_application_id' => :'api_application_id',
        :'embedded_signing' => :'embedded_signing',
        :'embedded_signing_notifications' => :'embedded_signing_notifications',
        :'text_tags' => :'text_tags',
        :'custom_requester_name' => :'custom_requester_name',
        :'custom_requester_email' => :'custom_requester_email',
        :'redirect_url' => :'redirect_url',
        :'allow_decline' => :'allow_decline',
        :'allow_reassign' => :'allow_reassign',
        :'decline_redirect_url' => :'decline_redirect_url',
        :'language' => :'language',
        :'metadata' => :'metadata',
        :'fields' => :'fields',
        :'attachment_requests' => :'attachment_requests',
        :'copied_contacts' => :'copied_contacts',
        :'labels' => :'labels',
        :'checkbox_groups' => :'checkbox_groups'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'test_mode' => :'Boolean',
        :'files' => :'Array<FilesInner>',
        :'name' => :'String',
        :'subject' => :'String',
        :'message' => :'String',
        :'recipients' => :'Array<RecipientsInner>',
        :'draft' => :'Boolean',
        :'self_sign' => :'Boolean',
        :'with_signature_page' => :'Boolean',
        :'expires_in' => :'Integer',
        :'reminders' => :'Boolean',
        :'apply_signing_order' => :'Boolean',
        :'api_application_id' => :'String',
        :'embedded_signing' => :'Boolean',
        :'embedded_signing_notifications' => :'Boolean',
        :'text_tags' => :'Boolean',
        :'custom_requester_name' => :'String',
        :'custom_requester_email' => :'String',
        :'redirect_url' => :'String',
        :'allow_decline' => :'Boolean',
        :'allow_reassign' => :'Boolean',
        :'decline_redirect_url' => :'String',
        :'language' => :'String',
        :'metadata' => :'Hash<String, String>',
        :'fields' => :'Array<Array<FieldsInnerInner>>',
        :'attachment_requests' => :'Array<AttachmentRequestsInner>',
        :'copied_contacts' => :'Array<CopiedContactsInner>',
        :'labels' => :'Array<LabelRequest>',
        :'checkbox_groups' => :'Array<CheckboxGroupsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SignWell::DocumentRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SignWell::DocumentRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'test_mode')
        self.test_mode = attributes[:'test_mode']
      else
        self.test_mode = false
      end

      if attributes.key?(:'files')
        if (value = attributes[:'files']).is_a?(Array)
          self.files = value
        end
      else
        self.files = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'message')
        self.message = attributes[:'message']
      end

      if attributes.key?(:'recipients')
        if (value = attributes[:'recipients']).is_a?(Array)
          self.recipients = value
        end
      else
        self.recipients = nil
      end

      if attributes.key?(:'draft')
        self.draft = attributes[:'draft']
      else
        self.draft = false
      end

      if attributes.key?(:'self_sign')
        self.self_sign = attributes[:'self_sign']
      else
        self.self_sign = false
      end

      if attributes.key?(:'with_signature_page')
        self.with_signature_page = attributes[:'with_signature_page']
      else
        self.with_signature_page = false
      end

      if attributes.key?(:'expires_in')
        self.expires_in = attributes[:'expires_in']
      end

      if attributes.key?(:'reminders')
        self.reminders = attributes[:'reminders']
      else
        self.reminders = true
      end

      if attributes.key?(:'apply_signing_order')
        self.apply_signing_order = attributes[:'apply_signing_order']
      else
        self.apply_signing_order = false
      end

      if attributes.key?(:'api_application_id')
        self.api_application_id = attributes[:'api_application_id']
      end

      if attributes.key?(:'embedded_signing')
        self.embedded_signing = attributes[:'embedded_signing']
      else
        self.embedded_signing = false
      end

      if attributes.key?(:'embedded_signing_notifications')
        self.embedded_signing_notifications = attributes[:'embedded_signing_notifications']
      else
        self.embedded_signing_notifications = false
      end

      if attributes.key?(:'text_tags')
        self.text_tags = attributes[:'text_tags']
      else
        self.text_tags = false
      end

      if attributes.key?(:'custom_requester_name')
        self.custom_requester_name = attributes[:'custom_requester_name']
      end

      if attributes.key?(:'custom_requester_email')
        self.custom_requester_email = attributes[:'custom_requester_email']
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      end

      if attributes.key?(:'allow_decline')
        self.allow_decline = attributes[:'allow_decline']
      else
        self.allow_decline = true
      end

      if attributes.key?(:'allow_reassign')
        self.allow_reassign = attributes[:'allow_reassign']
      else
        self.allow_reassign = true
      end

      if attributes.key?(:'decline_redirect_url')
        self.decline_redirect_url = attributes[:'decline_redirect_url']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'fields')
        if (value = attributes[:'fields']).is_a?(Array)
          self.fields = value
        end
      end

      if attributes.key?(:'attachment_requests')
        if (value = attributes[:'attachment_requests']).is_a?(Array)
          self.attachment_requests = value
        end
      end

      if attributes.key?(:'copied_contacts')
        if (value = attributes[:'copied_contacts']).is_a?(Array)
          self.copied_contacts = value
        end
      end

      if attributes.key?(:'labels')
        if (value = attributes[:'labels']).is_a?(Array)
          self.labels = value
        end
      end

      if attributes.key?(:'checkbox_groups')
        if (value = attributes[:'checkbox_groups']).is_a?(Array)
          self.checkbox_groups = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @files.nil?
        invalid_properties.push('invalid value for "files", files cannot be nil.')
      end

      if @recipients.nil?
        invalid_properties.push('invalid value for "recipients", recipients cannot be nil.')
      end

      if !@expires_in.nil? && @expires_in < 1
        invalid_properties.push('invalid value for "expires_in", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @files.nil?
      return false if @recipients.nil?
      return false if !@expires_in.nil? && @expires_in < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] files Value to be assigned
    def files=(files)
      if files.nil?
        fail ArgumentError, 'files cannot be nil'
      end

      @files = files
    end

    # Custom attribute writer method with validation
    # @param [Object] recipients Value to be assigned
    def recipients=(recipients)
      if recipients.nil?
        fail ArgumentError, 'recipients cannot be nil'
      end

      @recipients = recipients
    end

    # Custom attribute writer method with validation
    # @param [Object] expires_in Value to be assigned
    def expires_in=(expires_in)
      if expires_in.nil?
        fail ArgumentError, 'expires_in cannot be nil'
      end

      if expires_in < 1
        fail ArgumentError, 'invalid value for "expires_in", must be greater than or equal to 1.'
      end

      @expires_in = expires_in
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          test_mode == o.test_mode &&
          files == o.files &&
          name == o.name &&
          subject == o.subject &&
          message == o.message &&
          recipients == o.recipients &&
          draft == o.draft &&
          self_sign == o.self_sign &&
          with_signature_page == o.with_signature_page &&
          expires_in == o.expires_in &&
          reminders == o.reminders &&
          apply_signing_order == o.apply_signing_order &&
          api_application_id == o.api_application_id &&
          embedded_signing == o.embedded_signing &&
          embedded_signing_notifications == o.embedded_signing_notifications &&
          text_tags == o.text_tags &&
          custom_requester_name == o.custom_requester_name &&
          custom_requester_email == o.custom_requester_email &&
          redirect_url == o.redirect_url &&
          allow_decline == o.allow_decline &&
          allow_reassign == o.allow_reassign &&
          decline_redirect_url == o.decline_redirect_url &&
          language == o.language &&
          metadata == o.metadata &&
          fields == o.fields &&
          attachment_requests == o.attachment_requests &&
          copied_contacts == o.copied_contacts &&
          labels == o.labels &&
          checkbox_groups == o.checkbox_groups
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [test_mode, files, name, subject, message, recipients, draft, self_sign, with_signature_page, expires_in, reminders, apply_signing_order, api_application_id, embedded_signing, embedded_signing_notifications, text_tags, custom_requester_name, custom_requester_email, redirect_url, allow_decline, allow_reassign, decline_redirect_url, language, metadata, fields, attachment_requests, copied_contacts, labels, checkbox_groups].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SignWell::Models.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
end
