# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class DocumentTemplateResponse
      attr_accessor :id, :api_application_id, :requester_email_address, :custom_requester_name,
                    :custom_requester_email, :name, :subject, :message, :metadata, :created_at, :updated_at, :placeholders, :copied_placeholders, :status, :reminders, :archived, :template_link, :apply_signing_order, :redirect_url, :decline_redirect_url, :language, :expires_in, :files, :fields, :allow_decline, :allow_reassign, :labels, :checkbox_groups

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          'id': :id,
          'api_application_id': :api_application_id,
          'requester_email_address': :requester_email_address,
          'custom_requester_name': :custom_requester_name,
          'custom_requester_email': :custom_requester_email,
          'name': :name,
          'subject': :subject,
          'message': :message,
          'metadata': :metadata,
          'created_at': :created_at,
          'updated_at': :updated_at,
          'placeholders': :placeholders,
          'copied_placeholders': :copied_placeholders,
          'status': :status,
          'reminders': :reminders,
          'archived': :archived,
          'template_link': :template_link,
          'apply_signing_order': :apply_signing_order,
          'redirect_url': :redirect_url,
          'decline_redirect_url': :decline_redirect_url,
          'language': :language,
          'expires_in': :expires_in,
          'files': :files,
          'fields': :fields,
          'allow_decline': :allow_decline,
          'allow_reassign': :allow_reassign,
          'labels': :labels,
          'checkbox_groups': :checkbox_groups
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          'id': :String,
          'api_application_id': :String,
          'requester_email_address': :String,
          'custom_requester_name': :String,
          'custom_requester_email': :String,
          'name': :String,
          'subject': :String,
          'message': :String,
          'metadata': :'Hash<String, String>',
          'created_at': :Time,
          'updated_at': :Time,
          'placeholders': :'Array<DocumentTemplateResponsePlaceholdersInner>',
          'copied_placeholders': :'Array<DocumentTemplateResponseCopiedPlaceholdersInner>',
          'status': :String,
          'reminders': :Boolean,
          'archived': :Boolean,
          'template_link': :String,
          'apply_signing_order': :Boolean,
          'redirect_url': :String,
          'decline_redirect_url': :String,
          'language': :String,
          'expires_in': :Integer,
          'files': :'Array<FileInfo>',
          'fields': :'Array<Array<DocumentResponseFieldsInnerInner>>',
          'allow_decline': :Boolean,
          'allow_reassign': :Boolean,
          'labels': :'Array<LabelInfo>',
          'checkbox_groups': :'Array<CheckboxGroupInfo>'
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new(%i[
                  api_application_id
                  custom_requester_name
                  custom_requester_email
                  metadata
                  reminders
                  redirect_url
                  decline_redirect_url
                  expires_in
                  allow_decline
                  allow_reassign
                ])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        unless attributes.is_a?(Hash)
          raise ArgumentError,
                'The input argument (attributes) must be a hash in `SignWell::DocumentTemplateResponse` initialize method'
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) do |(k, v), h|
          unless acceptable_attribute_map.key?(k.to_sym)
            raise ArgumentError,
                  "`#{k}` is not a valid attribute in `SignWell::DocumentTemplateResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end

          h[k.to_sym] = v
        end

        self.id = (attributes[:id] if attributes.key?(:id))

        self.api_application_id = attributes[:api_application_id] if attributes.key?(:api_application_id)

        self.requester_email_address = attributes[:requester_email_address] if attributes.key?(:requester_email_address)

        self.custom_requester_name = attributes[:custom_requester_name] if attributes.key?(:custom_requester_name)

        self.custom_requester_email = attributes[:custom_requester_email] if attributes.key?(:custom_requester_email)

        self.name = attributes[:name] if attributes.key?(:name)

        self.subject = attributes[:subject] if attributes.key?(:subject)

        self.message = attributes[:message] if attributes.key?(:message)

        if attributes.key?(:metadata) && (value = attributes[:metadata]).is_a?(Hash)
          self.metadata = value
        end

        self.created_at = attributes[:created_at] if attributes.key?(:created_at)

        self.updated_at = attributes[:updated_at] if attributes.key?(:updated_at)

        if attributes.key?(:placeholders) && (value = attributes[:placeholders]).is_a?(Array)
          self.placeholders = value
        end

        if attributes.key?(:copied_placeholders) && (value = attributes[:copied_placeholders]).is_a?(Array)
          self.copied_placeholders = value
        end

        self.status = attributes[:status] if attributes.key?(:status)

        self.reminders = attributes[:reminders] if attributes.key?(:reminders)

        self.archived = attributes[:archived] if attributes.key?(:archived)

        self.template_link = attributes[:template_link] if attributes.key?(:template_link)

        self.apply_signing_order = attributes[:apply_signing_order] if attributes.key?(:apply_signing_order)

        self.redirect_url = attributes[:redirect_url] if attributes.key?(:redirect_url)

        self.decline_redirect_url = attributes[:decline_redirect_url] if attributes.key?(:decline_redirect_url)

        self.language = attributes[:language] if attributes.key?(:language)

        self.expires_in = attributes[:expires_in] if attributes.key?(:expires_in)

        if attributes.key?(:files) && (value = attributes[:files]).is_a?(Array)
          self.files = value
        end

        if attributes.key?(:fields) && (value = attributes[:fields]).is_a?(Array)
          self.fields = value
        end

        self.allow_decline = attributes[:allow_decline] if attributes.key?(:allow_decline)

        self.allow_reassign = attributes[:allow_reassign] if attributes.key?(:allow_reassign)

        if attributes.key?(:labels) && (value = attributes[:labels]).is_a?(Array)
          self.labels = value
        end

        return unless attributes.key?(:checkbox_groups)

        if (value = attributes[:checkbox_groups]).is_a?(Array)
          self.checkbox_groups = value
        end
      end

      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = []
        invalid_properties.push('invalid value for "id", id cannot be nil.') if @id.nil?

        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        return false if @id.nil?

        true
      end

      # Custom attribute writer method with validation
      # @param [Object] id Value to be assigned
      def id=(id)
        raise ArgumentError, 'id cannot be nil' if id.nil?

        @id = id
      end

      # Checks equality by comparing each attribute.
      # @param [Object] Object to be compared
      def ==(other)
        return true if equal?(other)

        self.class == other.class &&
          id == other.id &&
          api_application_id == other.api_application_id &&
          requester_email_address == other.requester_email_address &&
          custom_requester_name == other.custom_requester_name &&
          custom_requester_email == other.custom_requester_email &&
          name == other.name &&
          subject == other.subject &&
          message == other.message &&
          metadata == other.metadata &&
          created_at == other.created_at &&
          updated_at == other.updated_at &&
          placeholders == other.placeholders &&
          copied_placeholders == other.copied_placeholders &&
          status == other.status &&
          reminders == other.reminders &&
          archived == other.archived &&
          template_link == other.template_link &&
          apply_signing_order == other.apply_signing_order &&
          redirect_url == other.redirect_url &&
          decline_redirect_url == other.decline_redirect_url &&
          language == other.language &&
          expires_in == other.expires_in &&
          files == other.files &&
          fields == other.fields &&
          allow_decline == other.allow_decline &&
          allow_reassign == other.allow_reassign &&
          labels == other.labels &&
          checkbox_groups == other.checkbox_groups
      end

      # @see the `==` method
      # @param [Object] Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [id, api_application_id, requester_email_address, custom_requester_name, custom_requester_email, name, subject,
         message, metadata, created_at, updated_at, placeholders, copied_placeholders, status, reminders, archived, template_link, apply_signing_order, redirect_url, decline_redirect_url, language, expires_in, files, fields, allow_decline, allow_reassign, labels, checkbox_groups].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)

        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_s] = attributes[attribute_map[key]].map do |v|
                _deserialize(::Regexp.last_match(1), v)
              end
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param string type Data type
      # @param string value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
