=begin
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
  module Models
    class DocumentResponse
      # @return [Boolean]
      attr_accessor :test_mode

      # @return [String]
      attr_accessor :id

      # @return [String]
      attr_accessor :api_application_id

      # @return [String]
      attr_accessor :requester_email_address

      # @return [String]
      attr_accessor :custom_requester_name

      # @return [String]
      attr_accessor :custom_requester_email

      # @return [String]
      attr_accessor :name

      # @return [String]
      attr_accessor :subject

      # @return [String]
      attr_accessor :message

      # @return [Hash<String, String>]
      attr_accessor :metadata

      # @return [Time]
      attr_accessor :created_at

      # @return [Time]
      attr_accessor :updated_at

      # @return [Array<DocumentResponseRecipientsInner>]
      attr_accessor :recipients

      # Possible values: Draft, Created, Sending, Sent, Pending, Viewed, Completed, Manually completed, Declined, Canceled, Bounced, Blocked, Error, Expired
      # @return [String]
      attr_accessor :status

      # @return [Boolean]
      attr_accessor :reminders

      # @return [Boolean]
      attr_accessor :archived

      # @return [Boolean]
      attr_accessor :embedded_signing

      # @return [String]
      attr_accessor :embedded_edit_url

      # @return [String]
      attr_accessor :embedded_preview_url

      # @return [Boolean]
      attr_accessor :apply_signing_order

      # @return [String]
      attr_accessor :redirect_url

      # @return [String]
      attr_accessor :decline_redirect_url

      # @return [String]
      attr_accessor :language

      # @return [Integer]
      attr_accessor :expires_in

      # @return [String]
      attr_accessor :decline_message

      # @return [String]
      attr_accessor :error_message

      # @return [String]
      attr_accessor :template_id

      # @return [Array<String>]
      attr_accessor :template_ids

      # @return [Boolean]
      attr_accessor :embedded_signing_notifications

      # @return [Array<DocumentResponseAttachmentRequestsInner>]
      attr_accessor :attachment_requests

      # @return [Array<FileInfo>]
      attr_accessor :files

      # @return [Array<CopiedContactInfo>]
      attr_accessor :copied_contacts

      # @return [Array<Array<DocumentResponseFieldsInnerInner>>]
      attr_accessor :fields

      # @return [Boolean]
      attr_accessor :allow_decline

      # @return [Boolean]
      attr_accessor :allow_reassign

      # @return [Array<LabelInfo>]
      attr_accessor :labels

      # @return [Array<CheckboxGroupInfo>]
      attr_accessor :checkbox_groups

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          :'test_mode' => :'test_mode',
          :'id' => :'id',
          :'api_application_id' => :'api_application_id',
          :'requester_email_address' => :'requester_email_address',
          :'custom_requester_name' => :'custom_requester_name',
          :'custom_requester_email' => :'custom_requester_email',
          :'name' => :'name',
          :'subject' => :'subject',
          :'message' => :'message',
          :'metadata' => :'metadata',
          :'created_at' => :'created_at',
          :'updated_at' => :'updated_at',
          :'recipients' => :'recipients',
          :'status' => :'status',
          :'reminders' => :'reminders',
          :'archived' => :'archived',
          :'embedded_signing' => :'embedded_signing',
          :'embedded_edit_url' => :'embedded_edit_url',
          :'embedded_preview_url' => :'embedded_preview_url',
          :'apply_signing_order' => :'apply_signing_order',
          :'redirect_url' => :'redirect_url',
          :'decline_redirect_url' => :'decline_redirect_url',
          :'language' => :'language',
          :'expires_in' => :'expires_in',
          :'decline_message' => :'decline_message',
          :'error_message' => :'error_message',
          :'template_id' => :'template_id',
          :'template_ids' => :'template_ids',
          :'embedded_signing_notifications' => :'embedded_signing_notifications',
          :'attachment_requests' => :'attachment_requests',
          :'files' => :'files',
          :'copied_contacts' => :'copied_contacts',
          :'fields' => :'fields',
          :'allow_decline' => :'allow_decline',
          :'allow_reassign' => :'allow_reassign',
          :'labels' => :'labels',
          :'checkbox_groups' => :'checkbox_groups'
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          :'test_mode' => :'Boolean',
          :'id' => :'String',
          :'api_application_id' => :'String',
          :'requester_email_address' => :'String',
          :'custom_requester_name' => :'String',
          :'custom_requester_email' => :'String',
          :'name' => :'String',
          :'subject' => :'String',
          :'message' => :'String',
          :'metadata' => :'Hash<String, String>',
          :'created_at' => :'Time',
          :'updated_at' => :'Time',
          :'recipients' => :'Array<DocumentResponseRecipientsInner>',
          :'status' => :'String',
          :'reminders' => :'Boolean',
          :'archived' => :'Boolean',
          :'embedded_signing' => :'Boolean',
          :'embedded_edit_url' => :'String',
          :'embedded_preview_url' => :'String',
          :'apply_signing_order' => :'Boolean',
          :'redirect_url' => :'String',
          :'decline_redirect_url' => :'String',
          :'language' => :'String',
          :'expires_in' => :'Integer',
          :'decline_message' => :'String',
          :'error_message' => :'String',
          :'template_id' => :'String',
          :'template_ids' => :'Array<String>',
          :'embedded_signing_notifications' => :'Boolean',
          :'attachment_requests' => :'Array<DocumentResponseAttachmentRequestsInner>',
          :'files' => :'Array<FileInfo>',
          :'copied_contacts' => :'Array<CopiedContactInfo>',
          :'fields' => :'Array<Array<DocumentResponseFieldsInnerInner>>',
          :'allow_decline' => :'Boolean',
          :'allow_reassign' => :'Boolean',
          :'labels' => :'Array<LabelInfo>',
          :'checkbox_groups' => :'Array<CheckboxGroupInfo>'
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new([
          :'api_application_id',
          :'custom_requester_name',
          :'custom_requester_email',
          :'metadata',
          :'embedded_edit_url',
          :'embedded_preview_url',
          :'redirect_url',
          :'decline_redirect_url',
          :'decline_message',
          :'error_message',
          :'template_id',
          :'allow_decline',
          :'allow_reassign',
        ])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        if (!attributes.is_a?(Hash))
          fail ArgumentError, "The input argument (attributes) must be a hash in `SignWell::DocumentResponse` initialize method"
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) { |(k, v), h|
          if (!acceptable_attribute_map.key?(k.to_sym))
            fail ArgumentError, "`#{k}` is not a valid attribute in `SignWell::DocumentResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end
          h[k.to_sym] = v
        }

        if attributes.key?(:'test_mode')
          self.test_mode = attributes[:'test_mode']
        else
          self.test_mode = nil
        end

        if attributes.key?(:'id')
          self.id = attributes[:'id']
        else
          self.id = nil
        end

        if attributes.key?(:'api_application_id')
          self.api_application_id = attributes[:'api_application_id']
        end

        if attributes.key?(:'requester_email_address')
          self.requester_email_address = attributes[:'requester_email_address']
        end

        if attributes.key?(:'custom_requester_name')
          self.custom_requester_name = attributes[:'custom_requester_name']
        end

        if attributes.key?(:'custom_requester_email')
          self.custom_requester_email = attributes[:'custom_requester_email']
        end

        if attributes.key?(:'name')
          self.name = attributes[:'name']
        end

        if attributes.key?(:'subject')
          self.subject = attributes[:'subject']
        end

        if attributes.key?(:'message')
          self.message = attributes[:'message']
        end

        if attributes.key?(:'metadata')
          if (value = attributes[:'metadata']).is_a?(Hash)
            self.metadata = value
          end
        end

        if attributes.key?(:'created_at')
          self.created_at = attributes[:'created_at']
        end

        if attributes.key?(:'updated_at')
          self.updated_at = attributes[:'updated_at']
        end

        if attributes.key?(:'recipients')
          if (value = attributes[:'recipients']).is_a?(Array)
            self.recipients = value
          end
        end

        if attributes.key?(:'status')
          self.status = attributes[:'status']
        end

        if attributes.key?(:'reminders')
          self.reminders = attributes[:'reminders']
        end

        if attributes.key?(:'archived')
          self.archived = attributes[:'archived']
        end

        if attributes.key?(:'embedded_signing')
          self.embedded_signing = attributes[:'embedded_signing']
        end

        if attributes.key?(:'embedded_edit_url')
          self.embedded_edit_url = attributes[:'embedded_edit_url']
        end

        if attributes.key?(:'embedded_preview_url')
          self.embedded_preview_url = attributes[:'embedded_preview_url']
        end

        if attributes.key?(:'apply_signing_order')
          self.apply_signing_order = attributes[:'apply_signing_order']
        end

        if attributes.key?(:'redirect_url')
          self.redirect_url = attributes[:'redirect_url']
        end

        if attributes.key?(:'decline_redirect_url')
          self.decline_redirect_url = attributes[:'decline_redirect_url']
        end

        if attributes.key?(:'language')
          self.language = attributes[:'language']
        end

        if attributes.key?(:'expires_in')
          self.expires_in = attributes[:'expires_in']
        end

        if attributes.key?(:'decline_message')
          self.decline_message = attributes[:'decline_message']
        end

        if attributes.key?(:'error_message')
          self.error_message = attributes[:'error_message']
        end

        if attributes.key?(:'template_id')
          self.template_id = attributes[:'template_id']
        end

        if attributes.key?(:'template_ids')
          if (value = attributes[:'template_ids']).is_a?(Array)
            self.template_ids = value
          end
        end

        if attributes.key?(:'embedded_signing_notifications')
          self.embedded_signing_notifications = attributes[:'embedded_signing_notifications']
        end

        if attributes.key?(:'attachment_requests')
          if (value = attributes[:'attachment_requests']).is_a?(Array)
            self.attachment_requests = value
          end
        end

        if attributes.key?(:'files')
          if (value = attributes[:'files']).is_a?(Array)
            self.files = value
          end
        end

        if attributes.key?(:'copied_contacts')
          if (value = attributes[:'copied_contacts']).is_a?(Array)
            self.copied_contacts = value
          end
        end

        if attributes.key?(:'fields')
          if (value = attributes[:'fields']).is_a?(Array)
            self.fields = value
          end
        end

        if attributes.key?(:'allow_decline')
          self.allow_decline = attributes[:'allow_decline']
        end

        if attributes.key?(:'allow_reassign')
          self.allow_reassign = attributes[:'allow_reassign']
        end

        if attributes.key?(:'labels')
          if (value = attributes[:'labels']).is_a?(Array)
            self.labels = value
          end
        end

        if attributes.key?(:'checkbox_groups')
          if (value = attributes[:'checkbox_groups']).is_a?(Array)
            self.checkbox_groups = value
          end
        end
      end


      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = Array.new
        if @test_mode.nil?
          invalid_properties.push('invalid value for "test_mode", test_mode cannot be nil.')
        end

        if @id.nil?
          invalid_properties.push('invalid value for "id", id cannot be nil.')
        end

        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        return false if @test_mode.nil?
        return false if @id.nil?
        true
      end

      # Custom attribute writer method with validation
      # @param [Object] test_mode Value to be assigned
      def test_mode=(test_mode)
        if test_mode.nil?
          fail ArgumentError, 'test_mode cannot be nil'
        end

        @test_mode = test_mode
      end

      # Custom attribute writer method with validation
      # @param [Object] id Value to be assigned
      def id=(id)
        if id.nil?
          fail ArgumentError, 'id cannot be nil'
        end

        @id = id
      end

      # Checks equality by comparing each attribute.
      # @param [Object] other Object to be compared
      def ==(o)
        return true if self.equal?(o)
        self.class == o.class &&
            test_mode == o.test_mode &&
            id == o.id &&
            api_application_id == o.api_application_id &&
            requester_email_address == o.requester_email_address &&
            custom_requester_name == o.custom_requester_name &&
            custom_requester_email == o.custom_requester_email &&
            name == o.name &&
            subject == o.subject &&
            message == o.message &&
            metadata == o.metadata &&
            created_at == o.created_at &&
            updated_at == o.updated_at &&
            recipients == o.recipients &&
            status == o.status &&
            reminders == o.reminders &&
            archived == o.archived &&
            embedded_signing == o.embedded_signing &&
            embedded_edit_url == o.embedded_edit_url &&
            embedded_preview_url == o.embedded_preview_url &&
            apply_signing_order == o.apply_signing_order &&
            redirect_url == o.redirect_url &&
            decline_redirect_url == o.decline_redirect_url &&
            language == o.language &&
            expires_in == o.expires_in &&
            decline_message == o.decline_message &&
            error_message == o.error_message &&
            template_id == o.template_id &&
            template_ids == o.template_ids &&
            embedded_signing_notifications == o.embedded_signing_notifications &&
            attachment_requests == o.attachment_requests &&
            files == o.files &&
            copied_contacts == o.copied_contacts &&
            fields == o.fields &&
            allow_decline == o.allow_decline &&
            allow_reassign == o.allow_reassign &&
            labels == o.labels &&
            checkbox_groups == o.checkbox_groups
      end

      # @see the `==` method
      # @param [Object] other Object to be compared
      def eql?(o)
        self == o
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [test_mode, id, api_application_id, requester_email_address, custom_requester_name, custom_requester_email, name, subject, message, metadata, created_at, updated_at, recipients, status, reminders, archived, embedded_signing, embedded_edit_url, embedded_preview_url, apply_signing_order, redirect_url, decline_redirect_url, language, expires_in, decline_message, error_message, template_id, template_ids, embedded_signing_notifications, attachment_requests, files, copied_contacts, fields, allow_decline, allow_reassign, labels, checkbox_groups].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)
        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash["#{key}"] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param [String] type Data type
      # @param [String] value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        normalize_for_serialization! if respond_to?(:normalize_for_serialization!, true)

        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = self.send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
