=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
  class DocumentFromTemplateResponseFieldsInnerInner
    attr_accessor :x

    attr_accessor :y

    attr_accessor :page

    attr_accessor :recipient

    attr_accessor :api_id

    attr_accessor :name

    attr_accessor :date_format

    attr_accessor :fixed_width

    attr_accessor :label

    attr_accessor :lock_sign_date

    attr_accessor :required

    attr_accessor :type

    attr_accessor :validation

    attr_accessor :value

    attr_accessor :height

    attr_accessor :width

    attr_accessor :recipient_id

    attr_accessor :signing_elements_group_id

    attr_accessor :placeholder_name

    # Dropdown options (for dropdown/select fields)
    attr_accessor :options

    # Default selected option
    attr_accessor :default_option

    # Whether \"Other\" option is allowed
    attr_accessor :allow_other

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'x' => :'x',
        :'y' => :'y',
        :'page' => :'page',
        :'recipient' => :'recipient',
        :'api_id' => :'api_id',
        :'name' => :'name',
        :'date_format' => :'date_format',
        :'fixed_width' => :'fixed_width',
        :'label' => :'label',
        :'lock_sign_date' => :'lock_sign_date',
        :'required' => :'required',
        :'type' => :'type',
        :'validation' => :'validation',
        :'value' => :'value',
        :'height' => :'height',
        :'width' => :'width',
        :'recipient_id' => :'recipient_id',
        :'signing_elements_group_id' => :'signing_elements_group_id',
        :'placeholder_name' => :'placeholder_name',
        :'options' => :'options',
        :'default_option' => :'default_option',
        :'allow_other' => :'allow_other'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'x' => :'Float',
        :'y' => :'Float',
        :'page' => :'Integer',
        :'recipient' => :'DocumentFromTemplateResponseFieldsInnerInnerRecipient',
        :'api_id' => :'String',
        :'name' => :'String',
        :'date_format' => :'DateFormat',
        :'fixed_width' => :'Boolean',
        :'label' => :'String',
        :'lock_sign_date' => :'Boolean',
        :'required' => :'Boolean',
        :'type' => :'FieldType',
        :'validation' => :'TextValidation',
        :'value' => :'DocumentResponseFieldsInnerInnerValue',
        :'height' => :'String',
        :'width' => :'String',
        :'recipient_id' => :'String',
        :'signing_elements_group_id' => :'String',
        :'placeholder_name' => :'String',
        :'options' => :'Array<DocumentResponseFieldsInnerInnerOptionsInner>',
        :'default_option' => :'String',
        :'allow_other' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name',
        :'value',
        :'recipient_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SignWell::DocumentFromTemplateResponseFieldsInnerInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SignWell::DocumentFromTemplateResponseFieldsInnerInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'x')
        self.x = attributes[:'x']
      else
        self.x = nil
      end

      if attributes.key?(:'y')
        self.y = attributes[:'y']
      else
        self.y = nil
      end

      if attributes.key?(:'page')
        self.page = attributes[:'page']
      else
        self.page = nil
      end

      if attributes.key?(:'recipient')
        self.recipient = attributes[:'recipient']
      end

      if attributes.key?(:'api_id')
        self.api_id = attributes[:'api_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'date_format')
        self.date_format = attributes[:'date_format']
      end

      if attributes.key?(:'fixed_width')
        self.fixed_width = attributes[:'fixed_width']
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      end

      if attributes.key?(:'lock_sign_date')
        self.lock_sign_date = attributes[:'lock_sign_date']
      end

      if attributes.key?(:'required')
        self.required = attributes[:'required']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'validation')
        self.validation = attributes[:'validation']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      end

      if attributes.key?(:'height')
        self.height = attributes[:'height']
      end

      if attributes.key?(:'width')
        self.width = attributes[:'width']
      end

      if attributes.key?(:'recipient_id')
        self.recipient_id = attributes[:'recipient_id']
      end

      if attributes.key?(:'signing_elements_group_id')
        self.signing_elements_group_id = attributes[:'signing_elements_group_id']
      end

      if attributes.key?(:'placeholder_name')
        self.placeholder_name = attributes[:'placeholder_name']
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      end

      if attributes.key?(:'default_option')
        self.default_option = attributes[:'default_option']
      end

      if attributes.key?(:'allow_other')
        self.allow_other = attributes[:'allow_other']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @x.nil?
        invalid_properties.push('invalid value for "x", x cannot be nil.')
      end

      if @y.nil?
        invalid_properties.push('invalid value for "y", y cannot be nil.')
      end

      if @page.nil?
        invalid_properties.push('invalid value for "page", page cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @x.nil?
      return false if @y.nil?
      return false if @page.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] x Value to be assigned
    def x=(x)
      if x.nil?
        fail ArgumentError, 'x cannot be nil'
      end

      @x = x
    end

    # Custom attribute writer method with validation
    # @param [Object] y Value to be assigned
    def y=(y)
      if y.nil?
        fail ArgumentError, 'y cannot be nil'
      end

      @y = y
    end

    # Custom attribute writer method with validation
    # @param [Object] page Value to be assigned
    def page=(page)
      if page.nil?
        fail ArgumentError, 'page cannot be nil'
      end

      @page = page
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          x == o.x &&
          y == o.y &&
          page == o.page &&
          recipient == o.recipient &&
          api_id == o.api_id &&
          name == o.name &&
          date_format == o.date_format &&
          fixed_width == o.fixed_width &&
          label == o.label &&
          lock_sign_date == o.lock_sign_date &&
          required == o.required &&
          type == o.type &&
          validation == o.validation &&
          value == o.value &&
          height == o.height &&
          width == o.width &&
          recipient_id == o.recipient_id &&
          signing_elements_group_id == o.signing_elements_group_id &&
          placeholder_name == o.placeholder_name &&
          options == o.options &&
          default_option == o.default_option &&
          allow_other == o.allow_other
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [x, y, page, recipient, api_id, name, date_format, fixed_width, label, lock_sign_date, required, type, validation, value, height, width, recipient_id, signing_elements_group_id, placeholder_name, options, default_option, allow_other].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SignWell.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
