=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
module Models
  class FieldType
    INITIALS = "initials".freeze
    SIGNATURE = "signature".freeze
    CHECKBOX = "checkbox".freeze
    DATE = "date".freeze
    SELECT = "select".freeze
    TEXT = "text".freeze
    DROPDOWN = "dropdown".freeze
    AUTOFILL_COMPANY = "autofill_company".freeze
    AUTOFILL_EMAIL = "autofill_email".freeze
    AUTOFILL_FIRST_NAME = "autofill_first_name".freeze
    AUTOFILL_LAST_NAME = "autofill_last_name".freeze
    AUTOFILL_NAME = "autofill_name".freeze
    AUTOFILL_PHONE = "autofill_phone".freeze
    AUTOFILL_TITLE = "autofill_title".freeze
    AUTOFILL_DATE_SIGNED = "autofill_date_signed".freeze

    def self.all_vars
      @all_vars ||= [INITIALS, SIGNATURE, CHECKBOX, DATE, SELECT, TEXT, DROPDOWN, AUTOFILL_COMPANY, AUTOFILL_EMAIL, AUTOFILL_FIRST_NAME, AUTOFILL_LAST_NAME, AUTOFILL_NAME, AUTOFILL_PHONE, AUTOFILL_TITLE, AUTOFILL_DATE_SIGNED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FieldType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FieldType"
    end
  end
end
end
