# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class FileFormat
      PDF = 'pdf'
      ZIP = 'zip'

      def self.all_vars
        @all_vars ||= [PDF, ZIP].freeze
      end

      # Builds the enum from string
      # @param [String] value The enum value in the form of the string
      # @return [String] The enum value
      def self.build_from_hash(value)
        new.build_from_hash(value)
      end

      # Builds the enum from string
      # @param [String] value The enum value in the form of the string
      # @return [String] The enum value
      def build_from_hash(value)
        return value if FileFormat.all_vars.include?(value)

        raise "Invalid ENUM value #{value} for class #FileFormat"
      end
    end
  end
end
