# frozen_string_literal: true

# SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class TextValidation
      NO_TEXT_VALIDATION = 'no_text_validation'
      NUMBERS = 'numbers'
      LETTERS = 'letters'
      EMAIL_ADDRESS = 'email_address'
      US_PHONE_NUMBER = 'us_phone_number'
      US_ZIP_CODE = 'us_zip_code'
      US_SSN = 'us_ssn'
      US_AGE = 'us_age'
      ALPHANUMERIC = 'alphanumeric'
      US_BANK_ROUTING_NUMBER = 'us_bank_routing_number'
      US_BANK_ACCOUNT_NUMBER = 'us_bank_account_number'

      def self.all_vars
        @all_vars ||= [NO_TEXT_VALIDATION, NUMBERS, LETTERS, EMAIL_ADDRESS, US_PHONE_NUMBER, US_ZIP_CODE, US_SSN, US_AGE,
                       ALPHANUMERIC, US_BANK_ROUTING_NUMBER, US_BANK_ACCOUNT_NUMBER].freeze
      end

      # Builds the enum from string
      # @param [String] value The enum value in the form of the string
      # @return [String] The enum value
      def self.build_from_hash(value)
        new.build_from_hash(value)
      end

      # Builds the enum from string
      # @param [String] value The enum value in the form of the string
      # @return [String] The enum value
      def build_from_hash(value)
        return value if TextValidation.all_vars.include?(value)

        raise "Invalid ENUM value #{value} for class #TextValidation"
      end
    end
  end
end
