=begin
#SignWell Developer API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module SignWell
module Models
  class TextValidation
    NO_TEXT_VALIDATION = "no_text_validation".freeze
    NUMBERS = "numbers".freeze
    LETTERS = "letters".freeze
    EMAIL_ADDRESS = "email_address".freeze
    US_PHONE_NUMBER = "us_phone_number".freeze
    US_ZIP_CODE = "us_zip_code".freeze
    US_SSN = "us_ssn".freeze
    US_AGE = "us_age".freeze
    ALPHANUMERIC = "alphanumeric".freeze
    US_BANK_ROUTING_NUMBER = "us_bank_routing_number".freeze
    US_BANK_ACCOUNT_NUMBER = "us_bank_account_number".freeze

    def self.all_vars
      @all_vars ||= [NO_TEXT_VALIDATION, NUMBERS, LETTERS, EMAIL_ADDRESS, US_PHONE_NUMBER, US_ZIP_CODE, US_SSN, US_AGE, ALPHANUMERIC, US_BANK_ROUTING_NUMBER, US_BANK_ACCOUNT_NUMBER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TextValidation.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TextValidation"
    end
  end
end
end
