# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'date'
require 'time'

module SignWell
  module Models
    class UpdateDocumentAndSendRequest
      # Set to `true` to enable Test Mode. Documents created with Test Mode do not count towards API billing and are not legally binding. Defaults to `false`
      # @return [Boolean]
      attr_accessor :test_mode

      # The name of the document.
      # @return [String]
      attr_accessor :name

      # Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).
      # @return [String]
      attr_accessor :subject

      # Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).
      # @return [String]
      attr_accessor :message

      # Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).
      # @return [Integer]
      attr_accessor :expires_in

      # Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.
      # @return [Boolean]
      attr_accessor :reminders

      # When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.
      # @return [Boolean]
      attr_accessor :apply_signing_order

      # Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
      # @return [String]
      attr_accessor :api_application_id

      # When set to `true` it enables embedded signing in your website/web application. Embedded functionality works with an iFrame and email authentication is disabled. :embedded_signinig defaults to `false`.
      # @return [Boolean]
      attr_accessor :embedded_signing

      # On embedding signing, document owners (and CC'd contacts) do not get a notification email when documents have been completed. Setting this param to `true` will send out those final completed notifications. Default is `false`
      # @return [Boolean]
      attr_accessor :embedded_signing_notifications

      # Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.
      # @return [String]
      attr_accessor :custom_requester_name

      # Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.
      # @return [String]
      attr_accessor :custom_requester_email

      # A URL that recipients are redirected to after successfully signing a document.
      # @return [String]
      attr_accessor :redirect_url

      # Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.
      # @return [Boolean]
      attr_accessor :allow_decline

      # In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.
      # @return [Boolean]
      attr_accessor :allow_reassign

      # A URL that recipients are redirected to if the document is declined.
      # @return [String]
      attr_accessor :decline_redirect_url

      # Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.
      # @return [Hash<String, String>]
      attr_accessor :metadata

      # Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels. Updating labels on a document will replace any existing labels for that document.
      # @return [Array<LabelRequest>]
      attr_accessor :labels

      # Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.
      # @return [Array<CheckboxGroupsInner>]
      attr_accessor :checkbox_groups

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          'test_mode': :test_mode,
          'name': :name,
          'subject': :subject,
          'message': :message,
          'expires_in': :expires_in,
          'reminders': :reminders,
          'apply_signing_order': :apply_signing_order,
          'api_application_id': :api_application_id,
          'embedded_signing': :embedded_signing,
          'embedded_signing_notifications': :embedded_signing_notifications,
          'custom_requester_name': :custom_requester_name,
          'custom_requester_email': :custom_requester_email,
          'redirect_url': :redirect_url,
          'allow_decline': :allow_decline,
          'allow_reassign': :allow_reassign,
          'decline_redirect_url': :decline_redirect_url,
          'metadata': :metadata,
          'labels': :labels,
          'checkbox_groups': :checkbox_groups
        }
      end

      # Returns attribute mapping this model knows about
      def self.acceptable_attribute_map
        attribute_map
      end

      # Returns all the JSON keys this model knows about
      def self.acceptable_attributes
        acceptable_attribute_map.values
      end

      # Attribute type mapping.
      def self.openapi_types
        {
          'test_mode': :Boolean,
          'name': :String,
          'subject': :String,
          'message': :String,
          'expires_in': :Integer,
          'reminders': :Boolean,
          'apply_signing_order': :Boolean,
          'api_application_id': :String,
          'embedded_signing': :Boolean,
          'embedded_signing_notifications': :Boolean,
          'custom_requester_name': :String,
          'custom_requester_email': :String,
          'redirect_url': :String,
          'allow_decline': :Boolean,
          'allow_reassign': :Boolean,
          'decline_redirect_url': :String,
          'metadata': :'Hash<String, String>',
          'labels': :'Array<LabelRequest>',
          'checkbox_groups': :'Array<CheckboxGroupsInner>'
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new([])
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        unless attributes.is_a?(Hash)
          raise ArgumentError,
                'The input argument (attributes) must be a hash in `SignWell::UpdateDocumentAndSendRequest` initialize method'
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        acceptable_attribute_map = self.class.acceptable_attribute_map
        attributes = attributes.each_with_object({}) do |(k, v), h|
          unless acceptable_attribute_map.key?(k.to_sym)
            raise ArgumentError,
                  "`#{k}` is not a valid attribute in `SignWell::UpdateDocumentAndSendRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
          end

          h[k.to_sym] = v
        end

        self.test_mode = if attributes.key?(:test_mode)
                           attributes[:test_mode]
                         else
                           false
                         end

        self.name = attributes[:name] if attributes.key?(:name)

        self.subject = attributes[:subject] if attributes.key?(:subject)

        self.message = attributes[:message] if attributes.key?(:message)

        self.expires_in = attributes[:expires_in] if attributes.key?(:expires_in)

        self.reminders = if attributes.key?(:reminders)
                           attributes[:reminders]
                         else
                           true
                         end

        self.apply_signing_order = if attributes.key?(:apply_signing_order)
                                     attributes[:apply_signing_order]
                                   else
                                     false
                                   end

        self.api_application_id = attributes[:api_application_id] if attributes.key?(:api_application_id)

        self.embedded_signing = if attributes.key?(:embedded_signing)
                                  attributes[:embedded_signing]
                                else
                                  false
                                end

        self.embedded_signing_notifications = if attributes.key?(:embedded_signing_notifications)
                                                attributes[:embedded_signing_notifications]
                                              else
                                                false
                                              end

        self.custom_requester_name = attributes[:custom_requester_name] if attributes.key?(:custom_requester_name)

        self.custom_requester_email = attributes[:custom_requester_email] if attributes.key?(:custom_requester_email)

        self.redirect_url = attributes[:redirect_url] if attributes.key?(:redirect_url)

        self.allow_decline = if attributes.key?(:allow_decline)
                               attributes[:allow_decline]
                             else
                               true
                             end

        self.allow_reassign = if attributes.key?(:allow_reassign)
                                attributes[:allow_reassign]
                              else
                                true
                              end

        self.decline_redirect_url = attributes[:decline_redirect_url] if attributes.key?(:decline_redirect_url)

        if attributes.key?(:metadata) && (value = attributes[:metadata]).is_a?(Hash)
          self.metadata = value
        end

        if attributes.key?(:labels) && (value = attributes[:labels]).is_a?(Array)
          self.labels = value
        end

        return unless attributes.key?(:checkbox_groups)

        if (value = attributes[:checkbox_groups]).is_a?(Array)
          self.checkbox_groups = value
        end
      end

      # Show invalid properties with the reasons. Usually used together with valid?
      # @return Array for valid properties with the reasons
      def list_invalid_properties
        warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
        invalid_properties = []
        if !@expires_in.nil? && @expires_in < 1
          invalid_properties.push('invalid value for "expires_in", must be greater than or equal to 1.')
        end

        invalid_properties
      end

      # Check to see if the all the properties in the model are valid
      # @return true if the model is valid
      def valid?
        warn '[DEPRECATED] the `valid?` method is obsolete'
        return false if !@expires_in.nil? && @expires_in < 1

        true
      end

      # Custom attribute writer method with validation
      # @param [Object] expires_in Value to be assigned
      def expires_in=(expires_in)
        raise ArgumentError, 'expires_in cannot be nil' if expires_in.nil?

        raise ArgumentError, 'invalid value for "expires_in", must be greater than or equal to 1.' if expires_in < 1

        @expires_in = expires_in
      end

      # Checks equality by comparing each attribute.
      # @param [Object] other Object to be compared
      def ==(other)
        return true if equal?(other)

        self.class == other.class &&
          test_mode == other.test_mode &&
          name == other.name &&
          subject == other.subject &&
          message == other.message &&
          expires_in == other.expires_in &&
          reminders == other.reminders &&
          apply_signing_order == other.apply_signing_order &&
          api_application_id == other.api_application_id &&
          embedded_signing == other.embedded_signing &&
          embedded_signing_notifications == other.embedded_signing_notifications &&
          custom_requester_name == other.custom_requester_name &&
          custom_requester_email == other.custom_requester_email &&
          redirect_url == other.redirect_url &&
          allow_decline == other.allow_decline &&
          allow_reassign == other.allow_reassign &&
          decline_redirect_url == other.decline_redirect_url &&
          metadata == other.metadata &&
          labels == other.labels &&
          checkbox_groups == other.checkbox_groups
      end

      # @see the `==` method
      # @param [Object] other Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [test_mode, name, subject, message, expires_in, reminders, apply_signing_order, api_application_id,
         embedded_signing, embedded_signing_notifications, custom_requester_name, custom_requester_email, redirect_url, allow_decline, allow_reassign, decline_redirect_url, metadata, labels, checkbox_groups].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)

        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        openapi_types.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_s] = attributes[attribute_map[key]].map do |v|
                _deserialize(::Regexp.last_match(1), v)
              end
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
          end
        end
        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param [String] type Data type
      # @param [String] value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end
        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
        else # model
          # models (e.g. Pet) or oneOf
          klass = SignWell::Models.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end
        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.compact.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to? :to_hash
          value.to_hash
        else
          value
        end
      end
    end
  end
end
