# frozen_string_literal: true

# #SignWell Developer API
#
# API for creating, managing, and tracking electronic signature workflows.
#
# The version of the OpenAPI document: v1
# Contact: support@signwell.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

module SignWell
  module Errors
    # Base error class for all SignWell errors.
    class ApiError < StandardError
      attr_reader :code, :response_headers, :response_body, :body

      # Usage examples:
      #   ApiError.new
      #   ApiError.new("message")
      #   ApiError.new(:code => 500, :response_headers => {}, :response_body => "")
      #   ApiError.new(:code => 404, :message => "Not Found")
      def initialize(arg = nil)
        if arg.is_a? Hash
          if arg.key?(:message) || arg.key?('message')
            super(arg[:message] || arg['message'])
          else
            super arg
          end

          arg.each do |k, v|
            instance_variable_set "@#{k}", v
          end

          # Parse the response body as JSON if present
          if @response_body.is_a?(String) && !@response_body.empty?
            begin
              @body = JSON.parse(@response_body, symbolize_names: true)
            rescue JSON::ParserError
              @body = nil
            end
          end
        else
          super arg
          @message = arg
        end
      end

      # Override to_s to display a friendly error message
      def to_s
        message
      end

      def message
        msg = if @message.nil?
                'Error message: the server returns an error'
              else
                @message
              end

        msg += "\nHTTP status code: #{code}" if code
        msg += "\nResponse headers: #{response_headers}" if response_headers
        msg += "\nResponse body: #{response_body}" if response_body

        msg
      end
    end

    # Raised when the API returns a non-success HTTP status code.
    # Use ApiStatusError.for to construct the appropriate subclass.
    class ApiStatusError < ApiError
      # Factory method that returns the appropriate error subclass
      # based on the HTTP status code.
      #
      # @param code [Integer] HTTP status code
      # @param response_headers [Hash] Response headers
      # @param response_body [String] Raw response body
      # @param message [String] Error message
      # @return [ApiStatusError] An instance of the appropriate error subclass
      def self.for(code:, response_headers: nil, response_body: nil, message: nil)
        klass = case code
                when 400 then BadRequestError
                when 401 then AuthenticationError
                when 403 then PermissionDeniedError
                when 404 then NotFoundError
                when 409 then ConflictError
                when 422 then UnprocessableEntityError
                when 429 then RateLimitError
                else
                  code >= 500 ? InternalServerError : ApiStatusError
                end

        klass.new(
          code: code,
          response_headers: response_headers,
          response_body: response_body,
          message: message
        )
      end
    end

    # Raised when the API returns a 400 Bad Request response.
    class BadRequestError < ApiStatusError; end

    # Raised when the API returns a 401 Unauthorized response.
    class AuthenticationError < ApiStatusError; end

    # Raised when the API returns a 403 Forbidden response.
    class PermissionDeniedError < ApiStatusError; end

    # Raised when the API returns a 404 Not Found response.
    class NotFoundError < ApiStatusError; end

    # Raised when the API returns a 409 Conflict response.
    class ConflictError < ApiStatusError; end

    # Raised when the API returns a 422 Unprocessable Entity response.
    class UnprocessableEntityError < ApiStatusError; end

    # Raised when the API returns a 429 Too Many Requests response.
    class RateLimitError < ApiStatusError; end

    # Raised when the API returns a 5xx Internal Server Error response.
    class InternalServerError < ApiStatusError; end

    # Raised when the connection to the API server fails.
    class ApiConnectionError < ApiError; end

    # Raised when the connection to the API server times out.
    class ApiTimeoutError < ApiConnectionError; end
  end
end
