module SignwellSDK
  module Models
    module V1
      type bulk_send_retrieve_documents_params =
        { limit: Integer, page: Integer }
        & SignwellSDK::Internal::Type::request_parameters

      class BulkSendRetrieveDocumentsParams < SignwellSDK::Internal::Type::BaseModel
        extend SignwellSDK::Internal::Type::RequestParameters::Converter
        include SignwellSDK::Internal::Type::RequestParameters

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        def initialize: (
          ?limit: Integer,
          ?page: Integer,
          ?request_options: SignwellSDK::request_opts
        ) -> void

        def to_hash: -> {
          limit: Integer,
          page: Integer,
          request_options: SignwellSDK::RequestOptions
        }
      end
    end
  end
end
