module SignwellSDK
  module Models
    module V1
      type document_retrieve_params =
        {  } & SignwellSDK::Internal::Type::request_parameters

      class DocumentRetrieveParams < SignwellSDK::Internal::Type::BaseModel
        extend SignwellSDK::Internal::Type::RequestParameters::Converter
        include SignwellSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: SignwellSDK::request_opts) -> void

        def to_hash: -> { request_options: SignwellSDK::RequestOptions }
      end
    end
  end
end
