module SignwellSDK
  module Models
    module V1
      type document_retrieve_completed_pdf_response =
        SignwellSDK::Models::V1::DocumentRetrieveCompletedPdfResponse::Json
        | StringIO

      module DocumentRetrieveCompletedPdfResponse
        extend SignwellSDK::Internal::Type::Union

        type json = { file_url: String }

        class Json < SignwellSDK::Internal::Type::BaseModel
          attr_reader file_url: String?

          def file_url=: (String) -> String

          def initialize: (?file_url: String) -> void

          def to_hash: -> { file_url: String }
        end

        def self?.variants: -> ::Array[SignwellSDK::Models::V1::document_retrieve_completed_pdf_response]
      end
    end
  end
end
