module SignwellSDK
  module Models
    module V1
      type document_retrieve_nom151_certificate_params =
        { object_only: bool, url_only: bool }
        & SignwellSDK::Internal::Type::request_parameters

      class DocumentRetrieveNom151CertificateParams < SignwellSDK::Internal::Type::BaseModel
        extend SignwellSDK::Internal::Type::RequestParameters::Converter
        include SignwellSDK::Internal::Type::RequestParameters

        attr_reader object_only: bool?

        def object_only=: (bool) -> bool

        attr_reader url_only: bool?

        def url_only=: (bool) -> bool

        def initialize: (
          ?object_only: bool,
          ?url_only: bool,
          ?request_options: SignwellSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_only: bool,
          url_only: bool,
          request_options: SignwellSDK::RequestOptions
        }
      end
    end
  end
end
