module SignwellSDK
  module Models
    module V1
      type document_update_params =
        {
          allow_decline: bool,
          allow_reassign: bool,
          api_application_id: String,
          apply_signing_order: bool,
          checkbox_groups: ::Array[SignwellSDK::V1::CheckboxGroup],
          custom_requester_email: String,
          custom_requester_name: String,
          decline_redirect_url: String,
          embedded_signing: bool,
          embedded_signing_notifications: bool,
          expires_in: Integer,
          labels: ::Array[SignwellSDK::V1::Label],
          message: String,
          metadata: ::Hash[Symbol, String],
          name: String,
          redirect_url: String,
          reminders: bool,
          subject: String,
          test_mode: bool
        }
        & SignwellSDK::Internal::Type::request_parameters

      class DocumentUpdateParams < SignwellSDK::Internal::Type::BaseModel
        extend SignwellSDK::Internal::Type::RequestParameters::Converter
        include SignwellSDK::Internal::Type::RequestParameters

        attr_reader allow_decline: bool?

        def allow_decline=: (bool) -> bool

        attr_reader allow_reassign: bool?

        def allow_reassign=: (bool) -> bool

        attr_reader api_application_id: String?

        def api_application_id=: (String) -> String

        attr_reader apply_signing_order: bool?

        def apply_signing_order=: (bool) -> bool

        attr_reader checkbox_groups: ::Array[SignwellSDK::V1::CheckboxGroup]?

        def checkbox_groups=: (
          ::Array[SignwellSDK::V1::CheckboxGroup]
        ) -> ::Array[SignwellSDK::V1::CheckboxGroup]

        attr_reader custom_requester_email: String?

        def custom_requester_email=: (String) -> String

        attr_reader custom_requester_name: String?

        def custom_requester_name=: (String) -> String

        attr_reader decline_redirect_url: String?

        def decline_redirect_url=: (String) -> String

        attr_reader embedded_signing: bool?

        def embedded_signing=: (bool) -> bool

        attr_reader embedded_signing_notifications: bool?

        def embedded_signing_notifications=: (bool) -> bool

        attr_reader expires_in: Integer?

        def expires_in=: (Integer) -> Integer

        attr_reader labels: ::Array[SignwellSDK::V1::Label]?

        def labels=: (
          ::Array[SignwellSDK::V1::Label]
        ) -> ::Array[SignwellSDK::V1::Label]

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader redirect_url: String?

        def redirect_url=: (String) -> String

        attr_reader reminders: bool?

        def reminders=: (bool) -> bool

        attr_reader subject: String?

        def subject=: (String) -> String

        attr_reader test_mode: bool?

        def test_mode=: (bool) -> bool

        def initialize: (
          ?allow_decline: bool,
          ?allow_reassign: bool,
          ?api_application_id: String,
          ?apply_signing_order: bool,
          ?checkbox_groups: ::Array[SignwellSDK::V1::CheckboxGroup],
          ?custom_requester_email: String,
          ?custom_requester_name: String,
          ?decline_redirect_url: String,
          ?embedded_signing: bool,
          ?embedded_signing_notifications: bool,
          ?expires_in: Integer,
          ?labels: ::Array[SignwellSDK::V1::Label],
          ?message: String,
          ?metadata: ::Hash[Symbol, String],
          ?name: String,
          ?redirect_url: String,
          ?reminders: bool,
          ?subject: String,
          ?test_mode: bool,
          ?request_options: SignwellSDK::request_opts
        ) -> void

        def to_hash: -> {
          allow_decline: bool,
          allow_reassign: bool,
          api_application_id: String,
          apply_signing_order: bool,
          checkbox_groups: ::Array[SignwellSDK::V1::CheckboxGroup],
          custom_requester_email: String,
          custom_requester_name: String,
          decline_redirect_url: String,
          embedded_signing: bool,
          embedded_signing_notifications: bool,
          expires_in: Integer,
          labels: ::Array[SignwellSDK::V1::Label],
          message: String,
          metadata: ::Hash[Symbol, String],
          name: String,
          redirect_url: String,
          reminders: bool,
          subject: String,
          test_mode: bool,
          request_options: SignwellSDK::RequestOptions
        }
      end
    end
  end
end
