module SignwellSDK
  module Models
    module V1
      type hook_create_params =
        { callback_url: String, api_application_id: String }
        & SignwellSDK::Internal::Type::request_parameters

      class HookCreateParams < SignwellSDK::Internal::Type::BaseModel
        extend SignwellSDK::Internal::Type::RequestParameters::Converter
        include SignwellSDK::Internal::Type::RequestParameters

        attr_accessor callback_url: String

        attr_reader api_application_id: String?

        def api_application_id=: (String) -> String

        def initialize: (
          callback_url: String,
          ?api_application_id: String,
          ?request_options: SignwellSDK::request_opts
        ) -> void

        def to_hash: -> {
          callback_url: String,
          api_application_id: String,
          request_options: SignwellSDK::RequestOptions
        }
      end
    end
  end
end
