module SignwellSDK
  module Models
    module V1
      type template_checkbox_group =
        {
          checkbox_ids: ::Array[String],
          group_name: String,
          placeholder_id: String,
          exact_value: Integer,
          max_value: Integer,
          min_value: Integer,
          required: bool,
          validation: SignwellSDK::Models::checkbox_validation
        }

      class TemplateCheckboxGroup < SignwellSDK::Internal::Type::BaseModel
        attr_accessor checkbox_ids: ::Array[String]

        attr_accessor group_name: String

        attr_accessor placeholder_id: String

        attr_reader exact_value: Integer?

        def exact_value=: (Integer) -> Integer

        attr_reader max_value: Integer?

        def max_value=: (Integer) -> Integer

        attr_reader min_value: Integer?

        def min_value=: (Integer) -> Integer

        attr_reader required: bool?

        def required=: (bool) -> bool

        attr_reader validation: SignwellSDK::Models::checkbox_validation?

        def validation=: (
          SignwellSDK::Models::checkbox_validation
        ) -> SignwellSDK::Models::checkbox_validation

        def initialize: (
          checkbox_ids: ::Array[String],
          group_name: String,
          placeholder_id: String,
          ?exact_value: Integer,
          ?max_value: Integer,
          ?min_value: Integer,
          ?required: bool,
          ?validation: SignwellSDK::Models::checkbox_validation
        ) -> void

        def to_hash: -> {
          checkbox_ids: ::Array[String],
          group_name: String,
          placeholder_id: String,
          exact_value: Integer,
          max_value: Integer,
          min_value: Integer,
          required: bool,
          validation: SignwellSDK::Models::checkbox_validation
        }
      end
    end
  end
end
